### ISSUE TITLE
Default Fill Colour not working?

### ISSUE THREAD

**Issue by parksmart-dev** [ailon/markerjs2#1]
Hi,

Working great, except the default fill colour doesn't seem to be working.

```
 markerArea.settings.defaultColor = 'black';
 markerArea.settings.defaultFillColor = 'black';
markerArea.availableMarkerTypes = [markerjs2.EllipseMarker];
```

This just gives me a black outline when adding the Ellipse marker?

Any help appreciated.

Thanks

**Comment by ailon** [comment]
Looks like a bug though a direct fix would break the current default behavior. Let me sleep on it before I decide how to handle this.

**Comment by ailon** [comment]
It should respect the `defaultFillColor` starting with RC7. It's a potentially breaking change but I decided to fix it now while in pre-release. Hopefully, no one depended on it not working correctly yet.

**Comment by parksmart-dev** [comment]
Fantastic, thanks!
