### ISSUE TITLE
Error when inputting text markers

### ISSUE THREAD

**Issue by jeffinmotion** [ailon/markerjs2#10]
Hi Alan,

When I input a text marker and finish typing, if I click _inside_ of the marker area, the text area turns into normal marker that I can resize, as expected. But if I click anywhere _outside_ the marker area (like for example, another tool on the toolbar, or the save button), the text area blurs, but the element hasn't actually been created. If I then save the image without clicking inside the marker area, the text area disappears.

Jeff

**Comment by ailon** [comment]
Yes, looks like a bug. On it. Thanks!
