### ISSUE TITLE
TextMarker does not work as expected in mobile and pulls TextMarker data out of image

### ISSUE THREAD

**Issue by naveenchauhan123** [ailon/markerjs2#100]
TextMarker does not work as expected in mobile and pulls TextMarker data out of image

**Comment by ailon** [comment]
What browser/Android versions is this? Does it happen in this demo as well?
https://markerjs.com/demos/popup

Works fine for me on Android 12 in Chrome or Edge.

**Comment by naveenchauhan123** [comment]
use an mobile wallpaper or photo clicked from mobile and u will find that it zoom in the image and remains there in the same zoomed state forever.

**Comment by ailon** [comment]
Do you mean it happens on vertical images only or what are you trying to say? Can you please answer the questions? ;)

**Comment by naveenchauhan123** [comment]
Yes for vertical images..Thanks

**Comment by naveenchauhan123** [comment]
Solution For this fix:

after markerCreate:

do:

top:0
startManipulationTop:0
startManipulationY:0
left:0
startManipulationY:0
startManipulationLeft:0

**Comment by ailon** [comment]
This should be fixed in v2.21.6. Thank you for reporting this!

**Comment by naveenchauhan123** [comment]
Thanks A Lot! For Quick Response.
