### ISSUE TITLE
Setting Default Marker Tool

### ISSUE THREAD

**Issue by JGSolutions** [ailon/markerjs2#101]
Is there a way we can specific a selected marker tool. For example when the toolbar gets rendered instead of the selected tool being selected I would want the Free hand tool.

thanks

**Comment by ailon** [comment]
You can call `createNewMarker('FreehandMarker)` in a `show` event handler.

More about events [here](https://markerjs.com/docs/events/).

The demo on that page creates new marker after the previous one is created. Just swap the event you are handling and you should be all set:

```ts
markerArea.addEventListener("show", (event) => {
  event.markerArea.createNewMarker(markerjs2.FreehandMarker);
});
```

**Comment by JGSolutions** [comment]
thanks seems to work. When the markerView is closed do i need to remove the handler or dispose or something?

**Comment by JGSolutions** [comment]
we get this js error when drawing a marker then save it then we go back an draw another one

core.js:5967 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

  for (var t = this.markers.length - 1; t >= 0; t--) {
      this.setCurrentMarker(this.markers[t]), this.currentMarker.dispose(), this.markerImage.removeChild(this.currentMarker.container), this.markers.splice(this.markers.indexOf(this.currentMarker), 1);
    }

**Comment by ailon** [comment]
I guess you should create that marker in the `restorestate` event handler, not `show`.

**Comment by JGSolutions** [comment]
Thanks for the help. Everything seems to work.

**Comment by JGSolutions** [comment]
Not sure how to fix this issue with the undo. When we draw something with the free marker the undo does not not work. It goes to the select tool but the marked line stays. This happens only when one line is drawn

1. markerArea is loaded with free hand marker selected
2. draw a line
3. click undo
4. select mode
5. line is still there

**Comment by ailon** [comment]
This is probably due to the fact that undo doesn't work "within" the freehand tool (between separate strokes). I think for your scenario you should probably change the behavior to create a new marker for each stroke:
https://markerjs.com/reference/classes/settings.html#newfreehandmarkeronpointerup

**Comment by JGSolutions** [comment]
would i use it something like this?

this._markerEditor = new MarkerArea(targetElement);
this._markerEditor.settings.newFreehandMarkerOnPointerUp = true;

i tried this way doesn't work

**Comment by ailon** [comment]
"doesn't work" is not a very actionable comment :)

Here's a demo (works for me):
https://codesandbox.io/s/marker-js-2-freehand-from-the-start-6eoy3w?file=/src/index.js

**Comment by JGSolutions** [comment]
sorry actually meant couldn't get it to work. But we been doing some investigation and we have some piece of our code that is affecting some functionality

Thanks again

**Comment by JGSolutions** [comment]
this can be closed and resolved
