### ISSUE TITLE
Customizing resize grips

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#104]
Is there a straight forward way to tweak the designs of the resize grips? e.g. color, border, size. Thanks!

**Comment by ailon** [comment]
At the moment - no. But I'll add this to my to-do list.

**Comment by tarngerine** [comment]
Thank you!

**Comment by ailon** [comment]
I've dug a little deeper into this. Unfortunately, the UI settings are not passed down to markers where the grips are initiated. I don't want to add these to general settings as this is not where these settings belong. And I definitely don't want to change the marker API across the board to include UI style settings. So, I'll postpone this until some more significant update.

**Comment by tarngerine** [comment]
Understood, no problem! I can work around it hackily for now. Thank you!

**Comment by 5c0rp264** [comment]
@tarngerine Can you put a piece of code here to show how you hacked your way around  to change the size of the grips ?
Thank you !

**Comment by tarngerine** [comment]
Don’t have access to the code base anymore but I just used CSS selectors based on the DOM hierarchy :) fragile if the DOM ever changes for markerjs2 but works fine.
