### ISSUE TITLE
Request: add change event for MarkerAreaState

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#109]
I'm implementing in a React context and as per most React APIs, an `onChange` prop that is fired every time the MarkerAreaState changes (whatever we read in `getState()`) would be super handy to help with syncing/persisting changes live and activating any necessary side effects. In particular, `markerupdate` is missing from the events today, but i think a basic `statechange` event might also be nice.

**Comment by ailon** [comment]
Good points on both events. I will look into adding them.

**Comment by ailon** [comment]
Add both `statechange` for the whole area status change and `markerchange` for individual marker state change. Available now in v2.23

**Comment by tarngerine** [comment]
Thank you!
