### ISSUE TITLE
Markerjs2 placed incorrectly when triggered

### ISSUE THREAD

**Issue by atulrnt** [ailon/markerjs2#11]
Hi,

I'm trying to use markerjs2 in a project but when I implement the code from the examples, the elements that are generated when clicking on the image are not correctly aligned.

The attached screenshots show a basic example in a white page but the real implementation I'm trying to do is inside a bootstrap modal and the elements then appears under the modal on the top left corner of the page, it's not placed at all over the original image.

Do you have any idea why I get such position issues ?

Is it normal that the generated elements are inserted at the end of the DOM and not next the original image element ?

Here is my very simple vue component :
```vue
<template>
    <div class="marker-container">
        <img
                ref="screenshot"
                :src="screenshot"
                class="screenshot"
                @click="showMarkerArea"
        />
    </div>
</template>

<script>
    import * as markerjs2 from 'markerjs2';

    export default {
        name: "Annotation",
        props: {
            screenshot: {
                type: String,
                required: true,
            },
            screenshotId: {
                type: Number,
                required: true,
            },
        },
        methods: {
            showMarkerArea() {
                // create a marker.js MarkerArea
                const markerArea = new markerjs2.MarkerArea(this.$refs.screenshot);

                // attach an event handler to assign annotated image back to our image element
                markerArea.addRenderEventListener(dataUrl => {
                    this.$refs.screenshot.src = dataUrl;
                });

                // launch marker.js
                markerArea.show();
            },
        },
    }
</script>
```

<img width="871" alt="Capture d’écran 2021-03-08 à 15 47 58" src="https://user-images.githubusercontent.com/894203/110336973-b1333300-8025-11eb-8e46-db6fafb9033d.png">
<img width="871" alt="Capture d’écran 2021-03-08 à 15 48 03" src="https://user-images.githubusercontent.com/894203/110336995-b55f5080-8025-11eb-9c22-7ca4c9564bbf.png">
<img width="1021" alt="Capture d’écran 2021-03-08 à 15 52 40" src="https://user-images.githubusercontent.com/894203/110337555-564e0b80-8026-11eb-94af-ea1f4446a14e.png">

**Comment by ailon** [comment]
Have you tried setting `targetRoot` to the root element of your modal?
https://markerjs.com/reference/classes/markerarea.html#targetroot

**Comment by atulrnt** [comment]
Thank you very much for your quick response, that was the issue indeed !

It works great now.

**Comment by weirdyang** [comment]
Hi, sorry to bump this old issue, @atulrnt  how did you manage to place the toolbar above the image when displayed in a modal?

**Comment by weirdyang** [comment]
thanks resolved it using the offsetTop setting
