### ISSUE TITLE
Question: what are the purposes of visualTransformMatrix and containerTransformMatrix?

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#110]
I'm not seeing them really being used, curious what the purpose of them is. Thanks!

**Comment by ailon** [comment]
They are used to set the transforms on the rectangular markers (almost all of them). It has to do with the combination of moving and rotating markers correctly. Something I struggled with early on. To be honest, I can't remember the reason it can't be recreated from other values, but it works so I'm not keen on trying to see if it breaks otherwise ;)

**Comment by tarngerine** [comment]
I see, in my testing I never see the matrix change from (1 0 0, 1 0 0), and
reading the source code it doesn't seem like they're ever mutated from that
default. Just wanted to ask!
https://github.com/ailon/markerjs2/search?q=containertransformmatrix
<https://github.com/ailon/markerjs2/search?q=containertransformmatrix>

Thanks for the reply!

**Comment by ailon** [comment]
Try rotating a marker and you'll see `containerTransformMatrix` change.

**Comment by tarngerine** [comment]
Hmm, I am trying to look for the changes, but I don't see a matrix being set on the container — only the rotation transform?
 
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/1629901/185674917-8ba20553-ab99-4818-b824-b963520db394.png">

**Comment by ailon** [comment]
The matrix is just a compound representation of all other transformations applied. It saves all the transforms in one field when state is extracted/restored but is not explicitly manipulated from code.

**Comment by tarngerine** [comment]
Gotcha, thanks! Investigated and learned a bunch, left a new #118 in relation to this.
