### ISSUE TITLE
Request: make switchToSelectMode public

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#111]
I'm implementing a custom toolbar, and I'd like to replicate the functionality of the Select button, which deactivates the current active marker tool (set via `MarkerArea.createNewMarker`) allowing the user to select a marker on the canvas.
I'm not able to find an API for this. Thanks!

**Comment by ailon** [comment]
Yeah, `switchToSelectMode()` is private now. I'll make it public in the next release (unless I think of a reason not to).

**Comment by tarngerine** [comment]
Thank you!

**Comment by tarngerine** [comment]
Thank you!
