### ISSUE TITLE
Request: allow 'render' event listener to be awaited inside `startRenderAndClose`

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#112]
Repro: https://codesandbox.io/s/blue-http-q6oouz?file=/src/App.tsx

If I provide addEventListener or addRenderEventListener an `async` handler I would want to be able to await it via `startRenderAndClose`, but currently it does not await the handler I provide

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/1629901/185229449-2d597aee-d426-48df-8953-453b3dde457f.png">

**Comment by ailon** [comment]
Could you please elaborate on why you need this? Also, is this something any of the standard HTML elements do?

**Comment by tarngerine** [comment]
The reason I wanted this is because the library provides a `startRenderAndClose` which is awaitable, so I would expect that to include whatever code is being run within the render event listeners.

But to be fair this is not a pattern that standard HTML elements do. Not a big deal, I can find a workaround.
