### ISSUE TITLE
Behaviour Feature Enhancement With 'Render' Event

### ISSUE THREAD

**Issue by JGSolutions** [ailon/markerjs2#115]
Not an issue but more of an enhancement or if there is a way to get around it would be good too.

When adding a marker and then clicking on the checkmark to render the marking the toolbar closes. Is it possible to add a preventdefault on the render event to prevent closing the toolbar? Or is there away around it?

Thanks

**Comment by ailon** [comment]
Hi there. Unfortunately, there are some side-effects happening on rendering that make this impossible. However, you can reopen the editor back up right after rendering by calling `show()` again and restoring previous state.
