### ISSUE TITLE
Select a Framemarker inside another

### ISSUE THREAD

**Issue by 450Oucema** [ailon/markerjs2#116]
Hi,
I would like to know how to select a marker located inside another that has been and created before the 
largest marker.
I mean that it works when a marker is created after the largest, but not before.

On this screenshot, I created the pink marker after the yellow one, and if I want to select the yellow it selects the pink.
![image](https://user-images.githubusercontent.com/58775200/185942654-4a4a3a34-fc42-4e0e-b930-228d02f0732e.png)

I'm sorry if an issue has already been opened for this feature but I didn't find it.

**Comment by ailon** [comment]
The only way is to temporarily move the larger one out of the way, so it doesn't cover the smaller one.

**Comment by 450Oucema** [comment]
Okay that's what I was going to do. Thank you for your answer :).
