### ISSUE TITLE
Request: official way to change the current marker attributes

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#119]
Use case: I want to programatically change certain attributes of a selected marker, e.g. the size, the stroke color, if I'm making a custom Toolbox in a React context.

Currently I have to add an event listener for 'markerselect', whose event.marker is a `MarkerBase` according to Typescript definitions, but in actuality looks like an instance of the marker, which means protected methods like `setStrokeColor` are available. That works fine for me now, but I know this is not an officially sanctioned way to do this, and I'd love for there to be one.

**Comment by ailon** [comment]
Exposing the `set...` methods would be one thing but you would probably also want to access the current values, which would mean exposing those as well. And those are simple fields in most cases. To expose them "nicely" get accessor properties would have to be created. I'm not sure I want to do this in a minor update.

**Comment by tarngerine** [comment]
Totally fair, and again I'm not blocked, just wanted to share it!
