### ISSUE TITLE
Js function for remove a marker

### ISSUE THREAD

**Issue by MCVERTEX** [ailon/markerjs2#12]
Hi, I would like to use a custom button or keyboard shortcut for removing a marker, but I can't find a function like "deleteActiveMarker()" in the first version of markerjs,
I tried some shady things like 

```
const index = this.markerArea.markers.indexOf(this.markerArea.currentMarker);
				if (index > -1) {
					this.markerArea.markers.splice(index, 1);
				}
```
but with no success. Is there a correct way to do this with markerjs2 ?
Regards,

**Comment by MCVERTEX** [comment]
```
const index = this.markerArea.markers.indexOf(this.markerArea.currentMarker);
				if (index > -1) {
					this.markerArea.markers.splice(index, 1);
					this.markerArea.markerImage.removeChild(this.markerArea.currentMarker._container);
				}
```

This seems to work, you think it's a stable solution?

**Comment by ailon** [comment]
Technically, this is pretty much what's happening behind the scenes. If you could explain the scenario where/why you need this, I could properly expose a method for deleting current marker. Don't want to just do it without understanding the usecase, though.

**Comment by ailon** [comment]
That's what I thought :) I'll see if I can add a UI-less API for the next release (hopefully, next week) or I'll let you know if that turns out to be more complicated and requires more work.

**Comment by ailon** [comment]
I've exposed methods for creating and deleting markers in v2.5.0. And you can hide toolbar/toolbox too. I'll create a docs article about this later but in a nutshell here's a sample code:

```ts
  public openNoUI(target: HTMLImageElement): void {
    this.markerArea1 = new MarkerArea(target);
    this.markerArea1.addRenderEventListener(this.renderResult);

    // this.markerArea1.uiStyleSettings.toolbarHeight = 0;
    this.markerArea1.uiStyleSettings.hideToolbar = true;
    this.markerArea1.uiStyleSettings.hideToolbox = true;

    this.markerArea1.show();
    if (this.currentState) {
      this.markerArea1.restoreState(this.currentState);
    }
  }

  public addFrameMarker(): void {
    if (this.markerArea1) {
      this.markerArea1.createNewMarker(FrameMarker);
    }
  }
  public deleteCurrentMarker(): void {
    if (this.markerArea1) {
      this.markerArea1.deleteSelectedMarker();
    }
  }
  public renderAndClose(): void {
    if (this.markerArea1) {
      this.markerArea1.startRenderAndClose();
    }
  }

```
