### ISSUE TITLE
Bug: undoing destroys defs added via addDefs

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#120]
Repro: https://codesandbox.io/s/reverent-jepsen-mfihfd?file=/src/App.tsx

1. addDefs() after show()
2. observe the `<defs>` are there in `<svg>`
3. hit undo or call undo()
4. observe the `<defs>` is no longer inside `<svg>`

**Comment by ailon** [comment]
Yeah, I can see it and I think I know why this happens. Will investigate and fix. Thanks!
