### ISSUE TITLE
Request: allow single-clicking on a marker to select it, even when `createNewMarker` has been called

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#123]
Currently single-clicking when `createNewMarker` was called will create a marker with some default shape. In my experience we almost never want this default shape, and the click was either a) an accident or most likely b) a user trying to select a shape.

Context: we are doing that pattern where after a `markercreate` event, we call `createNewMarker` again to keep user in drawing mode for the current marker.

I would like to propose a fundamental change to selecting ux — which is that any time you single click on a marker, it is always with selection intent.

For example, Cleanshot implements this behavior, and it feels pretty good, even showing a grabby hand for affordance.

https://user-images.githubusercontent.com/1629901/186738857-b3c4d175-d9bc-4732-80da-7be5d164daae.mp4

**Comment by ailon** [comment]
I don't see a realistic way to do this with current internal architecture. Also, to be honest, I'm not sure this is a 100% good UX, and I can't justify the effort it would take to implement it as an optional behavior.

**Comment by tarngerine** [comment]
Totally reasonable, thanks!
