### ISSUE TITLE
Question: How to replace the current image while keeping editor open?

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#129]
I have a case where I'm performing some operation on the base source image that markerjs2 is annotating. I want to "refresh" the image while preserving markerjs2 state. Is there a way to "hot swap" this image without destroying/creating a new markerjs2 instance

**Comment by ailon** [comment]
You can use a non-image element (say, a div) overlayed on top of your image as the target parameter to the `MarkerArea` constructor:
https://markerjs.com/reference/classes/markerarea.html#constructor

This way you can change the image under the marker.js editor to anything you want. The only thing is that the resulting image is the marker layer only. You'll have to merge or reopen and resave if you want the result to be a flat marked image.

**Comment by tarngerine** [comment]
Gotcha, sounds like I need to reopen in this case then. Thanks!
