### ISSUE TITLE
Draw tool in Markerjs2

### ISSUE THREAD

**Issue by sai5yinc** [ailon/markerjs2#13]
The annotation draw tool is not working on IOS mobile browsers. can you help with this.

**Comment by ailon** [comment]
Just tried and it works for me. What phone and version of iOS you are seeing the issue on?

**Comment by sai5yinc** [comment]
working fine in android mobiles not working to iPhone devices only draw tool remaining tools are working.(version 14.4 iPhone  6s)

**Comment by ailon** [comment]
Unfortunately, I can't test it on iPhone 6s running iOS 14. Works fine on newer devices running iOS 14 so I'm not sure how to help here.
