### ISSUE TITLE
The quality of the image worsens when you add overlays with Marker.js2 (compared to the initial quality of the input image)

### ISSUE THREAD

**Issue by milaabl** [ailon/markerjs2#130]
Please have a look at this video: https://www.dropbox.com/s/jigyjdvryj36sgc/marker.js%202%20-%20All%20Defaults%20Demo%20-%20Google%20Chrome%202022-11-14%2015-56-55.mp4?dl=0

And at these 2 images: the first one is unedited and it's higher-quality, the second one is lower-quality as it was processed by Marker.js2.

Is this somehting canvas-specific that doesn't have a workaround?

![1](https://user-images.githubusercontent.com/86361434/201680837-58a18fc1-ae07-4d01-ad87-8062f5798219.png)

![2](https://user-images.githubusercontent.com/86361434/201680905-827fa41f-a350-46a1-bd9b-527a070dd161.png)

**Comment by ailon** [comment]
Check out [this article](https://markerjs.com/docs/rendering-options) on rendering options.

**Comment by milaabl** [comment]
Thank you, @ailon! Yes, adding `


  markerArea.renderAtNaturalSize = true;
  markerArea.renderImageType = "image/png";
  markerArea.renderImageQuality = 1;
` helped!
