### ISSUE TITLE
Question: Is there a way to change the width of popup container?

### ISSUE THREAD

**Issue by ylc395** [ailon/markerjs2#131]
https://github.com/ailon/markerjs2/blob/f57c0481b15bfbaa2d8273a5b485e44b6be2746a/src/MarkerArea.ts#L976

It seems that `100vw` is hard-coded. Is there a way to set it to other value, such as `100%` since `targetRoot` is probably not `document.body`?

**Comment by ailon** [comment]
Hmm... Could you elaborate on the use case in practical terms? My thinking is that popup is a popup in a window and shouldn't really care about the `targetRoot`. Otherwise, I would assume `inline` mode should make more sense. But maybe I'm missing something.

**Comment by ylc395** [comment]
If we use markerjs2's editor in a size-fixed container, inline mode doesn't help (editor's size depends on the image's size under inline mode). So I use popup mode instead. For example:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/12264626/203018162-fe594184-3d3b-49de-aeb8-d7a4e089edef.png">

**Comment by ailon** [comment]
Thanks! I'll think about it and look into it. I'm not 100% sure a simple change won't have any messed up side-effects.
