### ISSUE TITLE
Request: don't scale svg when zoom in or zoom out

### ISSUE THREAD

**Issue by ylc395** [ailon/markerjs2#132]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/12264626/203016331-50a728ce-845f-428e-bac0-0d4bdf69f020.png">

For example, when zoom in or zoom out, the circles' size will change too. This may reduce user experience.

**Comment by ailon** [comment]
Zooming is implemented in a very simple(istic) way right now - just scaling the div where canvas is placed. This won't change in the v2 timeframe. But I'll keep this in mind for v3.
