### ISSUE TITLE
[Question] Is is possible  when page load the image load with marker toolbar?

### ISSUE THREAD

**Issue by anubhabmondalDirac** [ailon/markerjs2#133]
Hello everyone,

I have added marker2.js to my project by using CDN. Now when clicking on the image the marker toolbar appears. 
Is there any way that when I load the page, the image appears with marker2 editing toolbar without clicking on the image?

Thanks in Advance!! @ailon

**Comment by ailon** [comment]
Sure. Why not? Instead of calling the `show()` method on the image click, call it on image's `load` event or some other event (depending on your implementation). Make sure that the image has finished loading before calling it though.
