### ISSUE TITLE
After edit send to server side?

### ISSUE THREAD

**Issue by nbao** [ailon/markerjs2#135]
Hello.
i have a question please.
is there any configuration for server side after change?
i just want to send the final image (base64) to php server by ajax and replace the original photo.

Thanks

**Comment by ailon** [comment]
Hi,

Sending to the server is out of scope of marker.js itself but can be easily implemented. Just google how to upload an image from a web front-end to the back end for your server-side technology of choice and that's exactly what you need to do with marker.js output.

I've referenced some examples here:
https://github.com/ailon/markerjs2/issues/88#issuecomment-1129825136

**Comment by nbao** [comment]
Yes of course it's very easy to upload image to server side but can you tell me how can I catch event the onclick save button on the top right and get current src base64 (if we have multiple marker on page)
