### ISSUE TITLE
Marker.js event listener thinks the cursor is ~30 px lower until a different marker gets added

### ISSUE THREAD

**Issue by milaabl** [ailon/markerjs2#137]
[element-bounds-screenshoter-v2 (10).zip](https://github.com/ailon/markerjs2/files/10405564/element-bounds-screenshoter-v2.10.zip)
The marker.js initialization and customization code is in the index.js on the lines in range 471 - 485.

We're building an extension that crops different areas on the screen. In previous versions of the extension, the marker.js worked well.

But after making some updates to the code and changing our capturing algorithms, despite the marker.js-related code staying the same as before, a bug occured.

The bug occurs on all of the websites I test it with.

What happens is when I click on the pen icon, present in the marker.js controls, and then hold the mouse and drag it to draw a line.

It is offset by ~30px. But when I try to add, for example, a rectangle, the line I've just drawn gets back to its proper position.

This is very strange.

Could you please advice me on what might be the culprit, @ailon ?

Here is the video: https://www.dropbox.com/s/umsp019tsohyf4g/CodePen_%20Online%20Code%20Editor%20and%20Front%20End%20Web%20Developer%20Community%20-%20Google%20Chrome%202023-01-12%2022-48-12.mp4?dl=0

The code is attached.

Please unpack the zip and upload it to the extensions tab. chrome://extensions

Just click on developer mode and then load unpacked

**Comment by milaabl** [comment]
@ailon , please let me know if you can reproduce

**Comment by ailon** [comment]
It looks like you have something affecting the canvas used to for drawing that free-hand marker. FreeHand marker is the only one that uses `canvas` for drawing but then it is "rendered" into an image object inside of SVG. So clearly something messes up that `canvas` but doesn't affect other parts. Could it be that you have something applying some styles to all "canvas" elements?

**Comment by milaabl** [comment]
@ailon , thank you so so much! I have a style in my index.css that applies some styling to all canvases. You're right, just have noticed that.

It works great now when I'm targeting the specific canvas by id instead of applying the style to all canvases.
