### ISSUE TITLE
Undo feature functions differently based on MarkerType: FreehandMarker

### ISSUE THREAD

**Issue by jljohnson001** [ailon/markerjs2#138]
Steps to reproduce:
* Select FreehandMarker icon
* Draw multiple shapes
* Select Undo

Expected behavior:
* Most recently drawn item is removed (other MarkerTypes appear to function this way)

Actual behavior:
* All items drawn using FreehandMarker are removed

**Note:** If this is expected behavior, I will modify my request to include this detail in Marker2JS docs.

**FreehandMarker**
![image](https://user-images.githubusercontent.com/66479094/218101358-e464254e-994f-4816-a756-8a32e56562cb.png)

**Undo**
![image](https://user-images.githubusercontent.com/66479094/218101395-92eac8dd-c545-4621-86b4-5c3b752f4a5a.png)

**Comment by ailon** [comment]
**FreehandMarker** is a very special type of marker in marker.js as the drawing is done in another context. So it only hits the "undo" subsytem after the drawing is done. The way to mitigate this is the [newFreehandMarkerOnPointerUp](https://markerjs.com/reference/classes/settings.html#newfreehandmarkeronpointerup) setting. This way undo will work as you expect, but each drawn part (mouse down to mouse up) will be a separate marker.

Good point about documenting this somewhere! Thank you.
