### ISSUE TITLE
Angles marker (zigzag)

### ISSUE THREAD

**Issue by kims89** [ailon/markerjs2#14]
Hello
First of all: Awesome project!

Is there a possibility to have or add angles on the point marker and line marker?

Picture for example
[https://i.ibb.co/JsQzZ6f/Screenshot-at-Apr-07-21-45-33.png](url)

**Comment by ailon** [comment]
Hi. Thanks for the kind words! 

Do you mean make some zigzag line marker? You can use several line markers to achieve the same end result but I don't think I see wide appeal of such a marker.

Having said that, you can develop your own markers for marker.js so everything is possible.

**Comment by kims89** [comment]
Yes, that's correct but not in a pattern (end user need to set the "angle" or "turn" on his own). 

Maybe not the most needed feature, but that is something I haven't seen in other similar libarys before, and would be a great addition to the other great tools that is allready implementet.

Need to take a look into make my own marker 🙂
