### ISSUE TITLE
Running markersj2 renderer on serverside? 

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#141]
e.g. with `node-canvas`

Curious if this is something that you've explored, but it's something we are investigating.

**Comment by ailon** [comment]
Hi there. Sorry, haven't tried that. Keep in mind that it not purely renders annotation data onto canvas, but actually creates the whole SVG thing using DOM and then renders it. So it would need the whole headless browser (or something) to render on the server.
