### ISSUE TITLE
CorpJS and MarkerJ2 - annotation are not rotate

### ISSUE THREAD

**Issue by aryanisml** [ailon/markerjs2#142]
Hi ,

Is there way to use both library corpJS and markerJS2 together as we can't rotate the annotation on image. 
We are using both the library in application. 
E.g.
Consider we have image and we are using makerJS2 library to apply annotation. Once we apply annotation we are rotating image through corp JS. After rotating image again we need to modify the annotation by using markerJS 2 .

**Comment by ailon** [comment]
Hi there,

No, that is not possible as it would add a ton of complexity to marker.js. So, it's only sequential: [crop] -> annotate -> [crop].

**Comment by aryanisml** [comment]
Thanks
