### ISSUE TITLE
Not able to set width and height in popup img Angular

### ISSUE THREAD

**Issue by karthin13** [ailon/markerjs2#144]
<img width="1440" alt="Screenshot 2023-04-04 at 6 44 04 PM" src="https://user-images.githubusercontent.com/38307606/229804702-36bb7ecd-53ef-4359-a429-54274987b133.png">

Angular code:
 const imageURL =
      "myimage.png";
    const img = new Image();
    img.onload = () => { 
      const markerArea = new markerjs2.MarkerArea(img);
      markerArea.settings.displayMode = "popup"; 
      markerArea.addRenderEventListener((imgURL) => {
        console.log("Image URL:", imgURL);
      });
      markerArea.show();
    };

---------------
I have tried lot in option to add height and width. not working . can you help on this.

**Comment by ailon** [comment]
You can't change image size in the `popup` mode - its purpose is specifically for editing images in full-size window and not in specific image size. You can still render the result in a specific or "natural" image size.

If you want to edit a specific size image in a modal dialog, just create your own "popup" and use marker.js in `inline` mode within it.
