### ISSUE TITLE
Arrows are sometimes drawn incorrectly

### ISSUE THREAD

**Issue by ermite1408** [ailon/markerjs2#146]
Hello! Thank you for beautiful library! I've already bought a licenses, but I found a small bug
Sometimes if I try to drawing a straight arrow, I got a wrong view.
You can reproduce it on your demos: https://markerjs.com/

- open "edit mode"
- select arrow
- drawn a straight arrow from top to bottom

**Browser**: Chrome
Version 112.0.5615.138 (Official Build) (32-bit)
**OS**: Windows 11

https://user-images.githubusercontent.com/57718126/233802537-3aab924c-944e-4e40-8700-23d9d76f315c.mp4

**Comment by ailon** [comment]
Thank you for reporting this! It's weird that no one encountered it until now :) I'll take a look and fix it.

**Comment by ailon** [comment]
This should be fixed now (v2.29.1 of markerjs2 and v1.1.1 of markerjs-live). Thank you for reporting!
