### ISSUE TITLE
marker cursor not visible over the color #808080 in images

### ISSUE THREAD

**Issue by mmattern** [ailon/markerjs2#149]
Here is my example forked from the CodeSandbox demo provided in the documentation:
https://codesandbox.io/s/marker-js-2-all-defaults-demo-forked-y4h17g

When you attempt to draw, the cursor is not visible. If you hover over the text in the image you can see part of the cursor though.

**Comment by ailon** [comment]
Hmm.. That's weird. marker.js uses "standard" built-in browser cursors. So, I'm not sure what can be done about this. Sounds like a browser issue. Maybe I could use some different cursor type than `crosshair`. Not sure which. But even then it feels like it would be a pretty drastic UX change for all users to address a specific almost theoretical issue.
