### ISSUE TITLE
Are there any events for clicking on marks?

### ISSUE THREAD

**Issue by hansenwebco** [ailon/markerjs2#15]
Hi,

I've read through the docs and your TS file and I can't find any support for an event when a mark is clicked.

Is there a way for me to receive an event with a mark is clicked, or do you plan on adding support for this in the future?

Thanks for an awesome library!

**Comment by ailon** [comment]
Hi Mark. 

There are no such events at the moment, but this is on my to-do list.

Can you describe a use-case you envision so that I have a realistic data-point when implementing this?

**Comment by bloolizard** [comment]
Would like this too.  Would want to save coordinates immediately whenever box is drawn.

**Comment by TimNZ** [comment]
I'd like these events for markers:

* Add
* Change props
* Delete
* Click

I'm building a system for people to give feedback on designs and will allow a comment/discussion feed for each marker.
So have granular knowledge of marker interactions/activity allows me to keep another part of the UI in sync.

**Comment by ailon** [comment]
@TimNZ hey Tim. Yes, this is still on my to-do list and now close to the top of it. When I finish another sub-project I will get to it.

There are some issues still to solve. For example, the "free hand" marker finishes "creating" when you switch to something else. So it could be weird one from the events perspective.

**Comment by TimNZ** [comment]
Forked and doing a real fast/dirty branch for a pull request for RFC.

My approach is just to over-communicate every operation and let the user decide what to do.
I cloned the render/close event handler mechanism, and created a MarkerEventHandler type that could roughly be:

``` 
{ 
    marker: MarkerBase
    type: string,
    data?: any
}

'type' is a string to allow Marker types to specify anything, and user can interpret in context of the type of marker,
and data for additional context data.

I'll do the pull request so you can play with something tangible to help with finalising a first release.

**Comment by ailon** [comment]
Hey Tim. Keep in mind that I don't accept pull requests.

I actually have the whole eventing system setup for another related project I'm working on. So the main thing left is putting in the work to apply it and figuring a few quirky areas like the one above.

**Comment by TimNZ** [comment]
No prob.
I want basic support right now and I'll get it done in the next 24 hrs.

You can look at the branch and see what I engineered to suit my needs and can decide if it inspires any change in your implementation.

**Comment by TimNZ** [comment]
https://github.com/TimNZ/markerjs2/tree/marker-events

Added public methods:

* addMarkerEventHandler
* removeMarkerEventHandler

Currently generates these events for markers:

* created
* selected
* deselected
* removed

Modified setCurrentMarker() to return early if the passed marker was already the current marker.  
Did not investigate if not checking for this has a legitimate reason?

All I'd want to add now is handling marker instance state change event, which I guess
requires MarkerBase and each marker implementation?

![image](https://user-images.githubusercontent.com/1051701/130412231-67b63f2b-8918-4dbd-80e6-d61f9df5b0ee.png)

**Comment by TimNZ** [comment]
Commited initial state-changed event support, 
triggers for manipulate() when state = move | rotate | resize, and explicit TextMarker state change i.e. text.
I think this is exactly what I want.

![image](https://user-images.githubusercontent.com/1051701/130416502-bdf5d95d-f8c8-4b64-b9a4-fbcf07c16006.png)

![image](https://user-images.githubusercontent.com/1051701/130417583-fac2fded-81b0-434f-a715-74a1c18ef68d.png)

**Comment by TimNZ** [comment]
I'm using my branch in production with a github tarball link and a postinstall script, so no rush! 😀

**Comment by ailon** [comment]
The new event system was added in v2.16. [Here are the docs](https://markerjs.com/docs/events).
