### ISSUE TITLE
Cannot change text popup inside modal

### ISSUE THREAD

**Issue by 7aklhz** [ailon/markerjs2#153]
Hi, 

This is my workflow: 
1- User clicks on a table row which opens a modal
2- In the modal body the user can add or annotated existing image
3- this opens the annotation in a "popup" (using markerArea.settings.displayMode = 'popup')
4- User ads text box.... but cannot edit the text 

I've tried to play around with z-index, display none, etc but cannot make it work. Any idea ? 

Thanks

**Comment by 7aklhz** [comment]
ok, for anyone else struggling with this, I solved it the following way
```
markerArea.addEventListener('markercreating', event => {
        document.getElementById("yourModal").style.display = "none";
    })

    markerArea.addEventListener('markerselect', event => {
        document.getElementById("yourModal").style.display = "none";
    })
```

Then, on addEventListener 'render' or 'close'  you add block again 
```
document.getElementById("tradesModal").style.display = "block";
```

Let me know if you have a better solution

**Comment by wildhart** [comment]
I'm having the same issue - text entry not working unless I hide my own modal first.

@ailon any ideas why this is happening?  Is there a cleaner solution?
