### ISSUE TITLE
Rendered dataUrl not correct

### ISSUE THREAD

**Issue by MatthieuPlaye** [ailon/markerjs2#155]
Hello, first of all thank you for this package. I have been trying MarkerJs today and there is a small issue when rendering the image where the annotations shift up. See examples bellow:

**Taken image with annotation (image was taken using the native camera api from capacitor (returns base64 format)**
<img width="406" alt="Taken picture" src="https://github.com/ailon/markerjs2/assets/125865974/c1997fd6-59af-4f8b-90ee-04205ea99a16">

**Rendered image from Markerjs**
<img width="406" alt="Rendered image" src="https://github.com/ailon/markerjs2/assets/125865974/9d688b28-0ca7-48d4-b101-8842499e5a35">

I also noticed that on a mobile device the top part of the image is hidden behind the 40px high toolbar.

**Tech stack**:
- Angular 16
- Ionic 7

**Comment by ailon** [comment]
Depending on where that image is placed within the DOM, etc. you may need to set [MarkerArea.targetRoot](https://markerjs.com/reference/classes/markerarea.html#targetroot) or some other setting. Hard to say without a repro.

**Comment by MatthieuPlaye** [comment]
I was able to fix the issue by placing a margin-top of 40px on the img tag and only load markerArea once the modal didPresent

```html
<ion-modal [canDismiss]="modalCanClose" (didPresent)="initMarkerJs()" [showBackdrop]="true">
  <ng-template>
    <ion-content>
      <div class="imageEditor" #target>
        <img [src]="selectedImage?.data" #img>
      </div>
    </ion-content>
  </ng-template>
</ion-modal>
```
