### ISSUE TITLE
Unable to render

### ISSUE THREAD

**Issue by 5c0rp264** [ailon/markerjs2#157]
Hello ! 

After any edition when I am trying to validate the markerjs2 interface do not close an I get the following error in the console. I tried the cdn and the release from this repo but still got the same error. I am VanillaJS and no other framework : 

`Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
`

**Comment by ailon** [comment]
Hi there,

This is a CORS issue. Try setting `crossorigin="anonymous"` attribute on your `img`.

**Comment by 5c0rp264** [comment]
Thank you, it resolves my problem in addition to changing the CORS policy on the image directory to allow for anonymous origin.

Have a nice day !
