### ISSUE TITLE
markerjs2.esm.js:1914 Error: <svg> attribute viewBox: Expected number, "0 0 885 NaN"

### ISSUE THREAD

**Issue by ShireenSyedAzad** [ailon/markerjs2#158]
<img width="346" alt="Screenshot 2023-07-23 at 3 12 14 PM" src="https://github.com/ailon/markerjs2/assets/126676909/7b8731b3-d7d2-427c-a173-90e126d48a84">

Image Height is returning NaN when displaying in popup mode
Tried to edit the imageHeight in showMarker Area function it's not working

Element returned for svg:
<svg xmlns="http://www.w3.org/2000/svg" width="825" height="NaN" viewBox="0 0 825 NaN" style="pointer-events: auto;"></svg>

How to fix this? 

<img width="511" alt="Screenshot 2023-07-23 at 10 28 06 AM" src="https://github.com/ailon/markerjs2/assets/126676909/6976889c-90f6-462f-87a0-cb6584525658">

**Comment by ailon** [comment]
I suspect this would have something to do with the page on which this is happening or the target image. Try setting explicit width/height on the image and see what happens. Also, could be that you call `showMarkerArea` before target image actually loads or something like that.

Hard to say without a repro.

**Comment by ailon** [comment]
Could be that you are operating inside of some `position: relative` container or something like that. You may need to set [targetRoot](https://markerjs.com/reference/classes/markerarea.html#targetroot) accordingly.

Hard to say without seeing an isolated repro.
