### ISSUE TITLE
Can we keep current marker enabled until another marker is clicked

### ISSUE THREAD

**Issue by fokrule** [ailon/markerjs2#16]
Hi, is there any way that once a marker is selected it will remain selected until next marker is activated. For instance, if arrow marker is selected currently it goes unselected after each arrow creation. To create a new arrow we need to click on arrow marker again and create a new arrow. So is it possible to do it like, selected marker will remain active until another marker is clicked.

**Comment by ailon** [comment]
There's no such feature at the moment but I can think about implementing it. This way you won't be able to select any previously created marker unless you click on the pointer/select button in the toolbar. Would that be a reasonable tradeoff for you?

**Comment by fokrule** [comment]
This will be fine for me. But I am little bit confused from user point of view. Will this be user friendly? Bit confused about this.

**Comment by razb** [comment]
> There's no such feature at the moment but I can think about implementing it. This way you won't be able to select any previously created marker unless you click on the pointer/select button in the toolbar. Would that be a reasonable tradeoff for you?

I think that's a fair trade-off. I realize that most vector drawing apps work the same way  with the tool defaulting back to a pointer after each selection, but the average user (in our use case) would be more familiar with paint/image editing tools that persist the last selected tool.  Perhaps this can be a configuration setting?

**Comment by ailon** [comment]
> Perhaps this can be a configuration setting?

Oh, I definitely not changing the default behavior. If I'm going to add this it will be behind a setting.

**Comment by ailon** [comment]
You can implement a custom solution to make this happen in v2.16 or higher. [Here's a demo](https://markerjs.com/demos/events).
