### ISSUE TITLE
Null pointer on resize

### ISSUE THREAD

**Issue by philipp-tailor** [ailon/markerjs2#164]
We've been getting the following NPE since upgrading from `2.21.4` to `2.29.6`. It's not happening every time that the viewport / the marker area is resized though. Haven't found any pattern.

![image](https://github.com/ailon/markerjs2/assets/47689073/3133cec7-cae4-44a1-a445-d7ccac070caa)

Please let me know if there's any implementation details that would help to understand what triggers the exception.

**Comment by ailon** [comment]
Hi. Thank you for reporting this. How often does this happen? I've tried to resize the default demo back-and-forth for some minutes but didn't get the error. So, I guess I'd need some more details or preferably a simple repro where it happens with some reasonable frequency. Also, does it happen in any browser or just some specific one? Thanks!

**Comment by philipp-tailor** [comment]
Waited a week with replying to answer the question how often this happens, but it's quite rare in my codebase. While it'd be nice to know and solve the root-cause, as consumer of the library I'd prefer the library to not throw when avoidable. Wondering if the function that's throwing here could swallow the error without it being irresponsible due to undesirable effects of handling the case with optional chaining / early exit etc.

**Comment by ailon** [comment]
@philipp-tailor yes, that's what I'll end up doing if I can't find the root cause. Will try to do some more experimenting today and will address it either way.

**Comment by ailon** [comment]
After some additional experimenting I still couldn't reproduce this, so ended up just adding additional guards around that statement. Please let me know if v2.29.9 fixes it for you.

**Comment by YLemelin09** [comment]
@ailon Seems to have fixed my issue.
