### ISSUE TITLE
Scrolling with touch 

### ISSUE THREAD

**Issue by ptrt-adriano** [ailon/markerjs2#166]
Hey there, I'm not sure this is an issue for the plugin or the application around it but reporting just in case:

On mobile, assuming the editor is open on an image, if the user, thru pinch zoom and dragging, end up with the editor area covering the whole screen, the user becomes unable to leave the editor or keep using the page as touch actions are disabled in the editor area. 

This results in the user having to reload the page, losing all unsaved annotations, unless rotating the screen exposes some area out of the editor.

The issue can be replicated on the demos in the site.

This doesn't look fixable on markerJS side as disabling touch actions appear to be essential for its functions so a workaround for the issue is setting the application max scale to a value that makes it impossible for the editors to cover the entire screen. Another possible workaround is to have a zoom out button always on screen floating over the editor.

**Comment by ailon** [comment]
I think the best approach for scenarios where this is a high probability scenario is to use marker.js in `popup` mode.

**Comment by ptrt-adriano** [comment]
I tried out the popup mode and while it added some constraints to the program, it works great on desktop but on mobile there are several issues with it (Should I open a new issue for those?).

The workarounds I suggested work but hurt the usability so I have been trying to run the package locally to pinpoint exactly what is preventing the drag on canvas. Being a newbie I initially thought it had something to do with the touch action attribute but that does not seem to be the case.

Testing with Responsive Design Mode on Firefox and Chrome the scrolling on canvas works normally but on an actual device it does not so I'm guessing in the current version this shouldn't have been an issue at all and it's instead an issue with the testing device i have?

Will get back to this if I uncover any new info.

**Comment by ptrt-adriano** [comment]
Hey, I found a solution.
The issue is caused by this line in MarkerArea.attachEvents:

`this.markerImage.addEventListener('touchmove', ev => ev.preventDefault());`

Which prevents dragging and zooming on the canvas on every situation.

To fix this I copied a piece of code from MarkerArea.onPointerDown and changed attachEvents like this:

```

  private attachEvents() {
    this.markerImage.addEventListener('pointerdown', this.onPointerDown);
    // workaround to prevent a bug with Apple Pencil
    // https://bugs.webkit.org/show_bug.cgi?id=217430
    this.markerImage.addEventListener('touchmove', ev => {
      if (this._currentMarker !== undefined && 
        (this._currentMarker.state === 'new' || this._currentMarker.state === 'creating')) {
        ev.preventDefault()
      } else if (this.mode === 'select') {
        const hitMarker = this.markers.find((m) => m.ownsTarget(ev.target));
        if (hitMarker !== undefined) {
          ev.preventDefault();
        } else {

        }
      }
    });

    this.markerImage.addEventListener('dblclick', this.onDblClick);
    this.attachWindowEvents();
  }
```

As far as I can tell, this makes it so that the event is prevented only if the user hasn't selected a marker for creation nor is touching on an existing marker, which allows the panning and zooming when not creating and clicking on a "clean area" which seems like a good compromise.

I have no idea if this will affect that "apple pencil bug" workaround, no device available to test it but works fine with touch on android.

If this fix is fine, it just needs some adjustments to remove code repetition between this and the onPointerDown.

**Comment by ailon** [comment]
There's also a case of panning when zoomed in, which I suspect your code interferes with. But if you don't need zooming/panning and this works for you then you can just use the mod.

**Comment by ptrt-adriano** [comment]
Haven't identified any issues with panning while zoomed.
After some testing I noticed that the fix works perfectly on Firefox but not on Chrome. For Chrome it works if the user starts a zoom in/out action and starts panning without releasing the touch, janky but it works.
