### ISSUE TITLE
Minimum marker size

### ISSUE THREAD

**Issue by kkeroo** [ailon/markerjs2#167]
Hello!

When i create small Frame markers they are resized to predefined default size. I looked the code and I see that in Rectangle ```RectangularBoxMarkerBase.ts``` in ```pointerUp()``` there is a hardcoded value of 10 for width and height meaning that everything smaller than 10 will be resized to default sizes. For my usecase this threshold of 10 is a little bit too much, i would want it lower. I could add variable the same way as variable ```defaultSize``` is defined but i have struggles with building out the forked repository. 

Is it possible that you incorporate this variable in original version because it is simple to do, and also we can manipulate this threshold with javascript?

If you dont find it useful to update the code, could you give me steps of building this repository the same way as is the node module? So i will be able to link forked repo with ```npm link```. I know that i have to compile TS and so on, but i never used TS before. This would help be a lot. 

Thanks 😃

**Comment by ailon** [comment]
The reason for that minimum is to prevent users from accidentally creating really tiny markers (with an accidental double click or releasing mouse button too quickly) that they can't manipulate afterwards. It gets really tricky with resize grips being larger than the marker itself.

I guess I could make that minimum configurable, but it won't make the tiny markers usable, so I'll start getting complaints about that :)

As for building, cloning the repository and then running `npm install` and then `npm run build` should be enough to rebuild it.

**Comment by kkeroo** [comment]
I understand. Thanks. It turns out i did not read the output of the build command. The required files are saved in ```dist``` folder.
