### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ganeshpc9265** [ailon/markerjs2#168]
Is there any way to **integrate** a font size dropdown or **font size panel** to Textmarker to change the font size to a specific pixel **rather than resizing** the text area.Please share if any code already exists.

**Comment by ailon** [comment]
Hi there. No, the text is always scaled to the marker boundaries. This may change in v3, but no drastic changes are planned for the 2.x branch in this area.

**Comment by ganeshpc9265** [comment]
Hi thanks for the response. In that case, I would like to know whether I could control the marker scale (width, height). Like is it possible to **disable scaling on drag** and change the **scale using a custom toolbox panel** for width & height!?

**Comment by ailon** [comment]
No. There are no such options, I'm afraid. marker.js is a tool to quickly place annotations on images. It's not a graphics editor with layout flexibility and precision goals.
