### ISSUE TITLE
Generate rasterized image on the fly from MarkerAreaState + original image

### ISSUE THREAD

**Issue by glterica** [ailon/markerjs2#17]
Hi @ailon,

First of all thank you very much for this great tool!

What do you think is the best way to store the MarkerAreaState (e.g., in a backend) in order to later fetch it and display the annotated image *without* opening the marker area first? Is there a way to do it without having to also store the annotated image alongside the MarkerAreaState?

Thanks!

**Comment by ailon** [comment]
Well, it's a browser library so on the backend you can only do it with something like Puppeteer.

Alternatively, you can save just the transparent marker layer (rather than MarkerAreaState) and superimpose it on the original image either on the client or on the server.

**Comment by glterica** [comment]
Sorry, I think my queation wasn't completely clear. What I meant was to display the annotated image on the client, without having to also store the marker layer image on the server (since this would be redundant, as all the information needed is already contained in the original image and MarkerAreaState which I'm storing). Is there a way to generate the rasterized annotated image overlay without opening the tool? Or to rephrase, is there a way to generate the base64 marker layer image from the MarkerAreaState on the client?

**Comment by glterica** [comment]
Ok, no problem, I'll try that. Thank you!

**Comment by ailon** [comment]
`renderState()` method has been added in v2.17 which does just that. Thank you for bring this up and your patience ;)
