### ISSUE TITLE
Add defaultText and defaultFontSize to TextMarker like CaptionFrameMarker

### ISSUE THREAD

**Issue by bennymeier** [ailon/markerjs2#177]
Hi,

I've seen that the `CaptionFrameMarker` has the options `defaultCaptionFontSize` and `defaultCaptionText`.
Is it possible to implement this also for `TextMarker` like `defaultFontSize` and `defaultText` because I think it's a valid use case. I would like to implement predefined markers like:
```js
{ defaultColor: "red", defaultText: "rejected", defaultFontSize: "2em" }
```
or
```js
{ defaultColor: "green", defaultText: "accepted", defaultFontSize: "2em" }
```

If I take a look into the `TextMarker.ts` it should be implemented easy because there is a `DEFAULT_TEXT`. This implementation would be fantastic!

Thanks a lot and have a great day,
Benny

**Comment by ailon** [comment]
The text marker works differently and always auto-sizes its content. I'm afraid this isn't going to change in the 2.x branch but for v3 it will work differently with a user-controlled font size.

**Comment by bennymeier** [comment]
Okay understandable. But what about the defaultText? Can you check an implementation for it?
