### ISSUE TITLE
Text Marker text not a property of Settings

### ISSUE THREAD

**Issue by socialmedialabs** [ailon/markerjs2#178]
When adding a text marker, the DEFAULT_TEXT is set to "_your text here_". While other text strings are configurable via the settings this one isn't. Why is that?

**Comment by ailon** [comment]
if by "other" you mean `CaptionMarker` then the answer is that this was added much later and kind of to the "specification" of the client who sponsored the feature :)

**Comment by socialmedialabs** [comment]
I guess what I'd actually like to see is an approach with the option for localization AND settings configuration. Again, we are about to purchase a license anyway but it would be helpful to have this feature, as well as the option to add custom buttons to the toolbar (_copy, paste, duplicate_ actions) and the toolbox.

**Comment by ailon** [comment]
All of this should be doable in v3 and if you buy a license now you'll get a free upgrade to v3.

**Comment by socialmedialabs** [comment]
Thanks again for your swift answer! Any rough estimation on when v3 will be available?

**Comment by ailon** [comment]
@socialmedialabs I don't want to give any ETAs that you can hold me accountable to 😅 Having said that, I really hope to release the non-final UI-less portion of it in Q1.

**Comment by socialmedialabs** [comment]
@ailon I can work with that, thank you ✌️
