### ISSUE TITLE
In MarkerArea.ts, showUI, this.target.top and this.target.left is incorrect for dynamically created images

### ISSUE THREAD

**Issue by herchenroder** [ailon/markerjs2#18]
Alan,

When I create a markerArea from an image in my application, the position does not match where the image appears on the screen. I believe this is because my images are dynamically created and perhaps the top and left values are relative to their containers instead of the absolute position on the page.

![image](https://user-images.githubusercontent.com/404741/115557999-4447c580-a280-11eb-8a14-818a37d2710e.png)

![image](https://user-images.githubusercontent.com/404741/115556474-b5867900-a27e-11eb-9cf1-416b2b080b38.png)

If I use getBoundingClientRect instead of target.offsetTop the markerArea displays where it should.

![image](https://user-images.githubusercontent.com/404741/115558717-01d2b880-a281-11eb-838c-bd80e8a61e24.png)

![image](https://user-images.githubusercontent.com/404741/115558564-df409f80-a280-11eb-94b0-ec9a0f4f7e70.png)

I believe this code change will address the issue:

![image](https://user-images.githubusercontent.com/404741/115557637-e3b88880-a27f-11eb-9464-9269b13f074c.png)

What do you think?

**Comment by ailon** [comment]
You should probably just set [MarkerArea.targetRoot](https://markerjs.com/reference/classes/markerarea.html#targetroot) and it should fix this.

**Comment by herchenroder** [comment]
I was just thinking - is it possible to insert the markerArea into the DOM just before the image element? It seems the marker is an absolute position DIV at the end of the page. If I drag it into the DOM just above the image, I don't need top and left positions. Just a thought. Thank You! 

![image](https://user-images.githubusercontent.com/404741/115560144-4f9bf080-a282-11eb-9fa9-6995e20f7624.png)

**Comment by ailon** [comment]
Have you tried the `targetRoot` approach?

**Comment by herchenroder** [comment]
I will try that! Thank You!

**Comment by herchenroder** [comment]
Incredible! This is exactly what I needed. All the marker areas are showing up right where they should. I have some adjustments to make for how the image is being show in the panels but that should be rather easy. Thank you so much!

![image](https://user-images.githubusercontent.com/404741/115586253-69493200-a29a-11eb-9925-24278279e4a3.png)

**Comment by ailon** [comment]
Glad it helped!
