### ISSUE TITLE
Callout annotation issue. Small text unreadable after saving

### ISSUE THREAD

**Issue by GaneshGunnala** [ailon/markerjs2#181]
I am trying to insert a callout marker and giving some text in it. however on save the text gets pixelated as it is small. Please provide a solution for this.
![as](https://github.com/react-native-maps/react-native-maps/assets/42089006/1fc0dc28-db43-4b42-909d-a76c30297102)

**Comment by ailon** [comment]
If the issue is "pixelation"/quality of the text, then you can address it by increasing the [rendering quality](https://markerjs.com/docs/rendering-options/). Otherwise, just make the whole callout bigger.
