### ISSUE TITLE
When text is long then the box is not resizing  automatically.

### ISSUE THREAD

**Issue by fokrule** [ailon/markerjs2#19]
Hi, I think there is an issue with the text marker. When I try to write little more text at that time those text are becoming too small. To view those text, it requires to resize the textbox manually and fit or read. 

![image](https://user-images.githubusercontent.com/30200108/116063208-8882fd80-a6a6-11eb-984a-2f721165cc71.png)

**Comment by ailon** [comment]
The behavior of the text marker is to fit text into the marker. As you mentioned, you can resize the marker if the text is too small or you can press enter while typing and have it on multiple lines.

Happy to hear ideas on how to improve this without adding additional layers of complexity.

**Comment by fokrule** [comment]
I have a suggestion on this. We can calculate the entered text length and based on text length we can set height or width of the text box.

**Comment by ailon** [comment]
Yeah, but then someone will complain that they wanted to fit the text into exactly that box and now they need to resize it ;)

**Comment by ailon** [comment]
Also, calculate based on what font size?

**Comment by fokrule** [comment]
Oh I see. That will be an issue as well. About calculation, length of the entered text.

**Comment by 7aklhz** [comment]
> The behavior of the text marker is to fit text into the marker. As you mentioned, you can resize the marker if the text is too small or you can press enter while typing and have it on multiple lines.
> 
> Happy to hear ideas on how to improve this without adding additional layers of complexity.

Would it be doable to make it the same as in Powerpoint that is 

1. either I create a text box and the text box size adapts to my content
2. either I create a text box with fixed size and the content adapts to the text box

So simply put, the default behavior would be the current behavior. But, if I would set a default width, so something like markerArea.settings.defaultWidth, then the text would automatically go to new line when hitting the end of the text box.
