### ISSUE TITLE
Svg Image cannot be rendered when render event is triggered

### ISSUE THREAD

**Issue by JingSheng02** [ailon/markerjs2#195]
I create a custom marker that follow the example of TriangleMarker, which i change the polygon to image and put the png, then when i open the marker area, i can drag and drop the marker well, but when i save, the image cannot be rendered. 

![Screenshot 2024-11-28 at 1 35 34 PM](https://github.com/user-attachments/assets/c4cc885f-06b7-4f47-934e-a70f66784b57)
![Screenshot 2024-11-28 at 1 35 50 PM](https://github.com/user-attachments/assets/de07d3d1-350c-49c4-9b54-8cd6c560944d)

HTML
`<div class="position-relative d-flex justify-content-center align-items-center p-0 m-0 marker-container"><img src="{{ asset('images/test2.jpeg') }}" alt="" class="w-100" id="unit-img" onclick="showMarker()"></div>`

Javascript
`let markerArea = new markerjs2.MarkerArea(document.getElementById('unit-img'));
            markerArea.settings.displayMode = 'popup';
            markerArea.targetRoot = document.querySelector('.marker-container');
            markerArea.availableMarkerTypes = [
                window.kioskMarker,
                window.pillarWrappingMarker,
                window.triangleMarker,
            ];
            markerArea.uiStyleSettings.zoomButtonVisible = true;
            markerArea.uiStyleSettings.zoomOutButtonVisible = true;
            markerArea.settings.defaultColor = '#082454';`
          
   pillar-wrapper-marker.js         
   
    createVisual() {
        this.visual = SvgHelper.createImage([
            ['href', 'http://localhost/images/pillar-wrapper.png'],
            ['width', '50'],
            ['height', '20'],
        ]);
        this.addMarkerVisualToContainer(this.visual);
    }

    setPoints() {
        super.setSize();
        SvgHelper.setAttributes(this.visual, [
            ['href', 'http://localhost/images/pillar-wrapper.png'],
            ['width', this.width],
            ['height', this.height],
        ]);
    }

**Comment by bennymeier** [comment]
Maybe you put some code so others can help you easier.

**Comment by JingSheng02** [comment]
> Maybe you put some code so others can help you easier.

 FYI, I've provided the code. Thanks for your help
