### ISSUE TITLE
It's not possible to add text on Android in 'popup' display mode

### ISSUE THREAD

**Issue by VepretskiyD** [ailon/markerjs2#20]
This issue occurs only on Android. On iOS, keyboard doesn't change viewport height.

Steps to reproduce:

1. Select 'text' tool
2. Tap somewhere on the image
3. Keyboard appears, viewport shrinks, keyboard closes

In my case it happens with both `inline` and `popup` display mode because body's height is 100vh. In case of `inline` mode I can set fixed height to the image container and it prevents target image from resizing, which makes text add/edit possible.

I'd appreciate any workaround for `popup` mode

https://user-images.githubusercontent.com/17052346/116522370-ccac1300-a8dd-11eb-9487-15f8b61366da.mp4

**Comment by ailon** [comment]
Yes, I'm literally working on a fix for this right now :) Thanks for reporting though!

**Comment by VepretskiyD** [comment]
That's great!

**Comment by VepretskiyD** [comment]
@ailon , may I ask when this fix will be available? It's very important for me

**Comment by ailon** [comment]
@VepretskiyD hopefully today. I'm already done with it. Need to do some more testing and fix another small related issue.

**Comment by VepretskiyD** [comment]
Great news! Thanks again

**Comment by ailon** [comment]
It's out now. Should fix this issue.

**Comment by VepretskiyD** [comment]
You saved my day. Works like a charm
