### ISSUE TITLE
Handle color event and save last used color

### ISSUE THREAD

**Issue by 7aklhz** [ailon/markerjs2#21]
Hi, 

I trying to achieve the following use case: 
"As a user, when I add, for example, a line or text to an image and change the color of that line or text to, for example, blue next time I add a line or text, the default color will be the last used color, that is blue".

Technically, the way I see this is as follows : 
1- detect/handle event when color is changed
2-set the default color to the selected color

I have the same question with line types : set the default line type (arrow, double arrow, simple) to last selected type.

I've read your documents but for the moment I'm unable to achieve this. Is it possible to achieve this use case and if so could you please explain how it's done ? 

Thank you.

**Comment by ailon** [comment]
Currently there's no proper way to do this. But I have it in my to-do list to make this a configurable behavior.

**Comment by 7aklhz** [comment]
Thank you for your response. Ok noted. 

In the meantime, I have a question : so what does "ColorChangeHandler" do and how to you make it work ?

**Comment by ailon** [comment]
It's an internal thing for when you make your own markers. Not meant to be used by "consumers" of the library.

**Comment by 7aklhz** [comment]
final question : any idea when you will have this more or less implemented 

PS : by the way, I really like your library. Saved my a lot of time and is really helpful

**Comment by ailon** [comment]
Thank you for the kind words!

I have this in the list for the next feature update but can't promise anything right now. Depends on other commitments and whether some pressing bugs are reported. Hopefully in the next couple of weeks. But if you are interested in purchasing a commercial license, I can speed it up ;)

**Comment by 7aklhz** [comment]
Hi

Did you manage to implement this ? It would also be great to have this for line thickness. 

Cheers.

**Comment by ailon** [comment]
As you can see above, `settings.defaultColorsFollowCurrentColors` was implemented back in may (released in version 2.7)
