### ISSUE TITLE
How to manually save the image

### ISSUE THREAD

**Issue by atulrnt** [ailon/markerjs2#22]
Hi,

For my project I need to be able to trigger the same action as the one triggered by the click on the save button.

I did succeed by doing something like that :

```js
markerArea = new markerjs2.MarkerArea(screenshot);
markerArea.addRenderEventListener((dataUrl) => {
    screenshot.src = dataUrl;
});

$('.my-custom-save-button').click(() => {
    await markerArea.renderClicked();

    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');

    // Set width and height
    canvas.width = $(screenshot).width();
    canvas.height = $(screenshot).height();

    // Draw the image
    ctx.drawImage(screenshot, 0, 0);

    const savedImage = canvas.toDataURL('image/png');
});
```

With this code I'm able to get the rasterized image out of marker.js to use it the way I want.

Everything is perfect except that it doesn't work in Firefox.
It works without issues in Chrome and Edge but in Firefox, I end up with only something like a quarter of the image and I don't understand why.

So now I'm thinking, there is probably a better way to do that.

Also, to remove the save and delete buttons that I don't need, I do as follow but again, there is probably a better way to do that : 

```js
$($($(markerArea.uiDiv.firstElementChild).find('.__markerjs2_toolbar_button')[9])[0]).hide();
$($($(markerArea.uiDiv.firstElementChild).find('.__markerjs2_toolbar_button')[10])[0]).hide();
```

Thank you in advance for your help !

**Comment by ailon** [comment]
Unless I misunderstand something, you can just use [`MarkerArea.startRenderAndClose()`](https://markerjs.com/reference/classes/markerarea.html#startrenderandclose)

**Comment by ailon** [comment]
Does pressing the save button in the toolbar work for you in Firefox? (seems to work fine for me in the demos)

**Comment by atulrnt** [comment]
When I press the button in Firefox, everything works perfectly but not when I use my script.

I also tried to fake the save button click by doing something like this `$button.click();` but I end up with the same issue, the annotations are not saved.

**Comment by ailon** [comment]
Thank you for the info. I will investigate.

**Comment by ailon** [comment]
Hmm.. Just tried and it seems to work fine for me with just this code:

```
    if (this.markerArea1) {
      this.markerArea1.startRenderAndClose();
    }
```

Do you have any extra details you can share? Or even better create a repro on Codesandbox or something?

**Comment by ailon** [comment]
Also, it's literally what the save button in the toolbar calls:

```
        case 'render': {
          this.startRenderAndClose();
          break;
        }
```

So there must be something else at play here.

**Comment by atulrnt** [comment]
Ok, after quite a lot of trials and errors, I finaly found the solution.
The problem was indeed coming from my code, not from your library.

I changed this initial code :
```js
markerArea = new markerjs2.MarkerArea(screenshot);
markerArea.addRenderEventListener((dataUrl) => {
    screenshot.src = dataUrl;
});

$('.my-custom-save-button').click(() => {
    await markerArea.renderClicked();

    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');

    // Set width and height
    canvas.width = $(screenshot).width();
    canvas.height = $(screenshot).height();

    // Draw the image
    ctx.drawImage(screenshot, 0, 0);

    const savedImage = canvas.toDataURL('image/png');
});
```

To this simplified one (I don't remember why I initially added this extra canvas manipulation but this was the faulty part) :
```js
markerArea = new markerjs2.MarkerArea(screenshot);
markerArea.addRenderEventListener((dataUrl) => {
    screenshot.src = dataUrl;
});

$('.my-custom-save-button').click(() => {
    await markerArea.renderClicked();

    const savedImage = screenshot.src;
});
```

Thank you very much for your help, I appreciate it and good job on your library, it deserve to be used by a lot more people !

**Comment by ailon** [comment]
Glad you worked it out. I would suggest using the `startRenderAndClose()` though as it's the official way and shouldn't change in the future versions (unlike the "hack" you used).
