### ISSUE TITLE
Is it possible to allow putting some icons

### ISSUE THREAD

**Issue by fokrule** [ailon/markerjs2#23]
Hi,
I don't have enough word to appreciate your efforts.
I have a request which might be helpful for other users also. Which is allow putting different types of icons. At lest few. Is it possible to add please.

**Comment by ailon** [comment]
This is on my to-do list buy I can't promise any ETA at the moment as I'm still brewing the best way to implement this from the user AND developer experience perspective.

**Comment by fokrule** [comment]
Great. Thanks
