### ISSUE TITLE
Issue with external images

### ISSUE THREAD

**Issue by dhananjayn** [ailon/markerjs2#27]
Hi,
Appreciate the app. It is wonderful. I am facing an issue where the image source is from an external source. The annotations are not saved in that case. Attached is the html code. Am I missing something? Thanks again.
-Dan
[index.txt](https://github.com/ailon/markerjs2/files/6532684/index.txt)

**Comment by ailon** [comment]
Make sure you set `crossorigin="anonymous"` on your `img` tag when loading external images

**Comment by dhananjayn** [comment]
That worked. Thanks.
