### ISSUE TITLE
By clicking undo button multiple times in a row, it highlights the entire image in blue

### ISSUE THREAD

**Issue by fokrule** [ailon/markerjs2#28]
hi, 
When we click undo button multiple times in a row, it highlights the entire image in blue color. Can we get rid of this. 

![image](https://user-images.githubusercontent.com/30200108/119599171-487a7c00-be06-11eb-89b0-42d62ead709d.png)

**Comment by ailon** [comment]
Thank you for reporting this! I can reproduce it and it actually happens with any toolbar button, not just undo.

I'll look into it.

**Comment by fokrule** [comment]
Thanks
