### ISSUE TITLE
Autosaving feature?

### ISSUE THREAD

**Issue by danrocha** [ailon/markerjs2#29]
Thank you for this library and all the effort you put into it.

Quick question: is there a good way to implement an autosave feature? 
For example, detecting whenever something changes within the marker area and autosave. 

We could detect clicks outside the marker area, or use an interval to save regularly, but were wondering if the library has any built-in, more performant way to achieve this?

**Comment by ailon** [comment]
Not at the moment. What you can do is save state on an interval but check if the current state is any different from the one you saved before.
