### ISSUE TITLE
RectangleMarker initialization

### ISSUE THREAD

**Issue by EmericDupil** [ailon/markerjs2#3]
Hello,

I want to create rectangle markers from the code that can then be edited by the user. So I try to create them with the RectangleMarker class but I don't understand what exactly the constructor parameters correspond to (despite the documentation). Would it be possible to have an example of initialization of a RectangleMarker or a more precise explanation of what its parameters (especially container, overlayContainer) correspond to ? 

Thanks

**Comment by ailon** [comment]
Hi there,

I'm afraid marker creation in v2 is interactive-only at this point. I will look into adding a way to create markers programmatically. If you could describe your scenario in some detail it would help me identify realistic use-cases for this.

Thanks!

Alan.

**Comment by EmericDupil** [comment]
Hi,

We work on computer vision and we already have markers that we need to display programmatically on markerjs2 so we can manually modify their settings (length, width, color...) and retrieve these new settings to work on it. 
Is there a way to do this from a JSON or the RectangleMarker class (or another class) ?

We managed to programmatically display a marker but the problem is that it cannot be modified. You can find the code sandbox here : https://codesandbox.io/s/markerjs-2-trying-to-add-markers-programmatically-icmmb

Emeric

**Comment by ailon** [comment]
So you need to place a marker in a specific position with a specific size, etc. programmatically and then be able to adjust it manually. Is this correct?

**Comment by EmericDupil** [comment]
Yes, this is correct.

**Comment by ailon** [comment]
A quick workaround would be to use [restore state functionality](https://markerjs.com/docs/saving-state). You can "reverse engineer" it so you can create your own state in code and then "restore" that state.

**Comment by EmericDupil** [comment]
It works with this workaround. 

Thank you!
