### ISSUE TITLE
Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.

### ISSUE THREAD

**Issue by danrocha** [ailon/markerjs2#30]
I am trying to pass this object to `markerArea.restoreState()`:

```js
// console log right before restoreState()
{
    "width": 671,
    "height": 356,
    "markers": [
        {
            "x1": 252.18359375,
            "x2": 392.7890625,
            "y1": 174.015625,
            "y2": 109.74609375,
            "state": "select",
            "typeName": "ArrowMarker",
            "arrowType": "end",
            "strokeColor": "#FF6E64",
            "strokeWidth": 3,
            "strokeDasharray": ""
        }
    ]
}
```

But I keep getting the error `Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.`. It seems somewhere inside of `restoreState()`, all the floats in the object above are turned into `NaN`:

<img src="https://user-images.githubusercontent.com/5139870/119673942-1421b280-be3c-11eb-96c4-217edfbc7e91.png"/>

Any ideas of what might be happening?

**Comment by ailon** [comment]
Did you get this state from marker.js or are you constructing it on your own? Also, do you call `restoreState()` after calling `show()`?

**Comment by danrocha** [comment]
This state was stored on a database, then retrieved, and attempted to be applied to the same original image. The idea is that we never store the annotated, rendered src, but only save the state object, to be applied at a later stage.

Yes, we do `.show()` before `.restoreState()` as in the demo.

**Comment by danrocha** [comment]
Unfortunately, my case has too many moving parts for a simple Codesandbox.

But I got it to work. It seems we were having timing issues. Adding a simple `setTimeout` before trying to show the marker area and restoring state within our component, as well as prefetching the base image, seems to make it work... 

Thanks for the prompt help, though!

**Comment by FaycalBorsali** [comment]
thak you @danrocha , I too needed to add a `setTimeout` before calling the `restoreState` .... same with `renderState`

@ailon is this a bug or are we using the library in an improper way ? 

When I debugged it, the error was thrown because (for some unknown reason) `markerArea.imageHeight` was set to `0` but when we run it after a very short timeout (I run it after 200ms), `markerArea.imageHeight` is no longer 0 but holds its true value so the above mentioned functions do their jobs correctly

**Comment by ailon** [comment]
@FaycalBorsali hard to say without a repro sample. There must be something specific to your scenario that's causing this as I have never experienced it myself and never got any other reports of the issue. So unless I can see it in action it's hard to debug.

**Comment by lliendo** [comment]
Hi,

Just want to mention that I can confirm this problem. The way to reproduce it is actually simple: just hard-code a variable with  previously logged to the console the output of `event.state`. Then after `show` immediately call `markerArea.restoreState(state)` (assuming state contains the previously saved state). This will throw the exception mentioned. Now when doing:

```js
markerArea.show();
debugger;
markerArea.restoreState(state);
```

from the browser after clicking to continue execution the image and the features will render properly. So I believe as previously mentioned this is related to some issue between `show` and `restoreState` as a `setTimeout` with in my case 100ms solves the bug.

Thanks,
Lucas.
