### ISSUE TITLE
Force FreehandMarker to end after each stroke?

### ISSUE THREAD

**Issue by danrocha** [ailon/markerjs2#31]
We created a custom toolbar that calls `createNewMarker()` functions to add markers to our marker area. 
All markers work the same, except the `FreehandMarker`. 

- When adding a `FrameMarker`, an `ArrowMarker`, or a `TextMarker`, the tool is automatically deselected after drawing; you can use the transformation handles and move the marker around; it is also registered in the state
- When adding a `FreehandMarker`, you can keep drawing until you select another tool; only then, all shapes drawn are stored as a single marker, and you can select it to use its transformation handles

We feel this is counterintuitive and would love to have the `FreehandMarker` behave like the other tools: as soon as you finish drawing a stroke, the stroke is selected, the handles are shown, and is stored in state.

Any simple way to do this? Or should we go ahead and dive into creating a custom marker?

**Comment by ailon** [comment]
Yes, there's a `newFreehandMarkerOnPointerUp` setting.

https://markerjs.com/reference/classes/settings.html#newfreehandmarkeronpointerup

**Comment by danrocha** [comment]
Thank you, I missed that.

It works well but, weirdly, every stroke is added **double** to the state. During the same session, it works fine, as both shapes behave as one. But when we `restoreState()` there are suddenly two of the same, behaving as single strokes.

Have you seen this before?

We could manually check and remove the duplicated marker from the state whenever added. How would you go about comparing two markers to see if they are the "same"?

**Comment by ailon** [comment]
Hmm.. Yes, I see this. Must have been introduced when trying to fix some other issue. I will look into it and fix it.

**Comment by ailon** [comment]
Fixed in 2.8.1
