### ISSUE TITLE
All the input field text can't be selected once marking started in the same page

### ISSUE THREAD

**Issue by fokrule** [ailon/markerjs2#33]
All the input field text can't be selected using mouse once marking started in the same page. Seems like mouse left button stop working.
Could you please suggest me something based on my below video. 
[https://drive.google.com/file/d/1UD-PxiwjsUwUfLCW84fXNL4bJ9L64Mwj/view?usp=sharing](url)

I can see it here as well. Once a marker is selected left cursor of the mouse keeps disabled.
https://markerjs.com/

**Comment by ailon** [comment]
I'll look into it.

**Comment by fokrule** [comment]
Thanksss
