### ISSUE TITLE
Text tool: after typing and clicking, text sometimes changes size

### ISSUE THREAD

**Issue by danrocha** [ailon/markerjs2#34]
We are adding text to our images by using a custom button that calls `markerArea.createNewMarker(markerjs2.TextMarker)`. Every time the text starts at the same scale. 

However, depending on how much text we type, after click outside the text box, the resulting text either enlarges or remains the same size (video: https://share.getcloudapp.com/Kou4Dm01)

Is this intentional? Any way to avoid this?

Thanks!!

**Comment by ailon** [comment]
This is by design. The text fills the marker rectangle. The only way to change the font size is to resize the text marker itself but I don't think you can do that from code (definitely not "officially").

**Comment by franciscolourenco** [comment]
@ailon would it be possible to make the marker rectangle fit the text instead? Thanks!

**Comment by ailon** [comment]
@franciscolourenco no, that would require font size controls and cause other issues/complexities.
