### ISSUE TITLE
Uncaught TypeError: can't access property "style", this.textEditor is undefined

### ISSUE THREAD

**Issue by danrocha** [ailon/markerjs2#35]
We use a custom button to place text markers on the image. 99% of the time it works, but every once in a while, when performing a `.restoreState()` after a `.show()` in an image with text markers, we get the following error:

![image](https://user-images.githubusercontent.com/5139870/120324136-913ea300-c2e6-11eb-83d3-730a4d6f88e2.png)

And the source map shows the error happens in this line:

![image](https://user-images.githubusercontent.com/5139870/120324266-b8957000-c2e6-11eb-8d5a-9b49787b2523.png)

We are not sure how to even begin debugging this! Is this a known issue? Any pointer of what to do to avoid this?

**Comment by ailon** [comment]
Hmm... This doesn't make much sense to me as this code path should only execute when in "editing" mode (which only happens with user interaction).

I had a hunch that maybe this happens when you click render/ok while editing text but this doesn't happen on my machine. Can you test this scenario on your code? I mean create a marker and render (get state) while TextMarker is in editing state and then try to restore from that state.

**Comment by danrocha** [comment]
That seems to be it. 

In our application we never `.render()`. We save the state as a JSON in the DB, and then do a `.show()` `.restoreState()` as soon as the image is loaded. 

If we are editing text but do not click outside of the text (to finish editing and show the edit handles) and save the state, it saves the marker state with the text marker containing `state: "edit"`.

I tried to run a `.deselect()` in all existing markers before saving the state, but the TextMarker still goes on with `state: "edit"` to our store. 

How would you go about making sure the markers are in "select" state before saving the state? Or would it be better to check it before `restoreState()`?

**Comment by ailon** [comment]
There are two angles here:

1) this is clearly a bug on our side and should be fixed. However...
2) technically correct behavior in this state would be launching into editing mode on `restoreState()` and I'm not sure this is what you want to happen. Is it?

If not, there's a `MarkerArea.setCurrentMarker()` method that with no parameter deselects any current marker and that would probably fix your issue. However, if you are using TypeScript it is marked `private` and you'd have to work around that to call it for now. I'll think about making it public instead (probably no harm in that).
