### ISSUE TITLE
Blurred image output in popup.

### ISSUE THREAD

**Issue by shikhar2333** [ailon/markerjs2#39]
Image gets blurred on opening the Annotation toolbar in popup mode. Is there a way to fix the styling of the popup so that the original image dimensions are retained?

**Comment by ailon** [comment]
Hi. There's no such option at the moment - the images are always scaled to fill in the popup mode. I've added a setting for this to the to-do list.

For now, if that's a common issue in your use-case, I suggest creating your own popup and then using marker.js in inline mode within it as a workaround.

**Comment by shikhar2333** [comment]
The blurred image problem also happens if you repeatedly click on save when in inline mode. Each time the save is clicked, the image gets zoomed on even more and hence becomes blurry.

**Comment by ailon** [comment]
`renderAtNaturalSize` and `renderImageQuality` settings should take care of that. Check this docs article for details:
https://markerjs.com/docs/rendering-options/
