### ISSUE TITLE
Annotating SVG images

### ISSUE THREAD

**Issue by afrozl** [ailon/markerjs2#40]
I am attempting to annotate SVG images, however I am unable to save the resulting image as I get an error

`markerjs2.esm.js?4931:15 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Image.h.onload (webpack-internal:///./node_modules/markerjs2/markerjs2.esm.js:47:5795)`

Setting  `markerArea.renderMarkersOnly  = true;` gets rid of the error, but then only the annotation is saved. I could combine the 2 layers myself, but was hoping there was a way to do so in markerjs.

**Comment by ailon** [comment]
First depending on your setup, you may need a `crossorigin="anonymous"` attribute on the img tag. But, IIRC, there may be something inside the SVG that is referencing other elements that may prevent this from working anyway. Having said that, I've just tried it with a simple SVG and it worked fine.

**Comment by afrozl** [comment]
I think it might be easiest to just bind to `addCloseEventListener` and overlay  the annotation on top of the base SVG image prior to saving/uploading. Is there a way to get the SVG string for the annotation rather than the image blob?

**Comment by ailon** [comment]
No, the "pure" annotation SVG doesn't exist in marker.js as it actually is a set of more complex objects (with manipulation boxes and grips hidden when rendered). So making an annotation SVG would require some extra code to extract just the visible parts from the "behind-the-scenes" SVG.

But I guess you can "hack" into it and get the whole thing anyway.

**Comment by afrozl** [comment]
Appreciate the quick responses.  I guess my use case is a little different from the norm. We're working with very detailed scatter plots and keeping the saved/uploaded images as SVG is crucial since it allows for extended zooming without loss of resolution.

I'll dig into the code to see where I can tap into the annotation flow. I'm happy to  purchase the license, but hopefully we won't be breaking any terms of the license agreement by "hacking" the code.

**Comment by ailon** [comment]
That would be fine with the license as long as you keep in mind that you may have to reapply your mod when new versions are released.

I'm also planning a companion library that would display the generated markup in some dynamic and/or interactive (or just static) way. Seems like it would be a good fit for your needs.

**Comment by razb** [comment]
That companion library sounds like exactly what I need. In the meantime, I was able to get what I needed by hooking into the `t.prototype.rasterize` function to grab the raw SVG string.

**Comment by afrozl** [comment]
I'll wait for the companion library, but the "hack" also works for now.

**Comment by TimNZ** [comment]
@ailon I hit the cross origin/tainted issue, and once i sorted AWS S3 CORS config, still getting the error on Chrome.
Use a cache buster query string solved it.
https://www.hacksoft.io/blog/handle-images-cors-error-in-chrome

A FAQ for common issues would be great.

GREAT work on this library - thanks.
Will buy a license soon.

**Comment by ailon** [comment]
Good to know, Tim! Thanks for the tip. I'll need to investigate this deeper and yes, FAQ is in the books :)
