### ISSUE TITLE
Ellipse as highlighter

### ISSUE THREAD

**Issue by afrozl** [ailon/markerjs2#43]
Is it possible to add an ellipse highlighter? or perhaps a way to set the default opacity for the EllipseMarker?

**Comment by ailon** [comment]
There's no built-in way to do this but I think it should be very easy to extend EllipseMarker and just set the opacity to a different value in the constructor in that, say, `HighlightEllipseMarker`

Here's a docs article on creating your own markers but this one should be even more simple.
https://markerjs.com/docs/extend-markerjs

**Comment by afrozl** [comment]
That worked perfectly. Here is the code in case anyone else wants to do something similar

```
import {
  EllipseMarker
} from "markerjs2";

export class HighlightEllipseMarker extends EllipseMarker {
  constructor(container, overlayContainer, settings) {
    super(container, overlayContainer, settings);
    this.strokeWidth = 0
    this.opacity = 0.25;
  }
}

HighlightEllipseMarker.typeName = "HighlightEllipseMarker";
HighlightEllipseMarker.title = "Ellipse Highlighter";
HighlightEllipseMarker.icon = '<svg viewBox="0 0 24 24"><path d="M12 4C6.5 4 2 7.58 2 12s4.5 8 10 8 10-3.58 10-8-4.5-8-10-8z"/></svg>';

```

**Comment by afrozl** [comment]
I feel I must have missed something obvious, but the custom markers are not getting saved in state and thus not available when restoring state.

**Comment by afrozl** [comment]
Never mind, I really should read the docs before raising an issue. Just had to add getState and restoreState to the custom marker definitions https://markerjs.com/docs/extend-markerjs.
