### ISSUE TITLE
Removing markerArea

### ISSUE THREAD

**Issue by afrozl** [ailon/markerjs2#45]
Is there a "destroy" method to remove an existing  markerArea?

**Comment by Reykugo-Gear** [comment]
markerarea is initiate by a class `new MarkerArea(...)` so  i think you can simply use  `delete myMarkerAreaInstance`

**Comment by aruprakshit** [comment]
> If you remember to call the `close` method before destroying the object, it'll remove the global event handlers.

I think I have similar [issue](https://github.com/ailon/markerjs/issues/61) , somehow I created it to the old lib. Can you tell me how to close or destroy the marker object?
