### ISSUE TITLE
Safari: text do not scale nor translate when resizing

### ISSUE THREAD

**Issue by vpusher** [ailon/markerjs2#46]
Either using the raw text or the text bubble, when resizing the marker, the text does not get translated or scaled.

If the marker is double clicked to edit the text, the position and scale get fixed.

**Incorrect (after resize)**

<img width="611" alt="Screenshot 2021-06-25 at 17 40 39" src="https://user-images.githubusercontent.com/3390457/123450334-eb2c4300-d5dc-11eb-8321-f527b8180ed5.png">

**Correct (after double click)**

<img width="613" alt="Screenshot 2021-06-25 at 17 40 51" src="https://user-images.githubusercontent.com/3390457/123450368-f54e4180-d5dc-11eb-9846-5759597f387f.png">

It seems to work on Edge/Chrome. Most probably a Webkit issue...

Safari 14.1.1 / macOS Big Sur 11.4

**Comment by ailon** [comment]
Thanks! I've received a similar report just recently and will hopefully fix it next week.

**Comment by vpusher** [comment]
@ailon, works great! thanks!
