### ISSUE TITLE
Alternative to `.startRenderAndClose()` to fire render event listener?

### ISSUE THREAD

**Issue by danrocha** [ailon/markerjs2#47]
Hello,

Is there an alternative to `.startRenderAndClose()` which would fire the render event listener without closing the tool? 

I would like to save the annotated image while keeping the marker tool open.

**Comment by danrocha** [comment]
I guess I could just do:

```js
this.markerArea.render().then(dataUrl => {
  // save the image
})
```

right?

**Comment by ailon** [comment]
> I guess I could just do:
> 
> ```js
> this.markerArea.render().then(dataUrl => {
>   // save the image
> })
> ```
> 
> right?

Probably yes, but this unselects currently active marker and could have other side-effects. "Officially" there's no way to render while editing but if this method works for you it should probably continue to work (no guarantees though).
