### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ronsiverd** [ailon/markerjs2#5]
My company recently purchased the license for the markerjs2 library and I imported it into my project at work.  I just wanted to say thank you as it's working great.   I did come across two features that would be nice if ever the possibility of adding them were to arise.  One would be to enable deleting a selected marker by pressing the delete key instead of clicking on the trash can.  Second, would be provide a way when initially loading an image to show the saved off marker data.  I am currently saving off the marker data, which works great with a single session of making annotations on an image.  However, it would be nice to be able to come back to an image at a later date and be able to pass the saved off marker data to display on the image without having to first launch the editor and run through the addRenderEventListener method.  Thank you and please let me know if you have any questions.

**Comment by ailon** [comment]
Hi there,

Thank you for the kind words!

1) yes, delete key deletion is on my to-do list and should be added at some point in not too distant future.
2) I'm not sure I understand correctly what's missing in [saving & restoring state](https://markerjs.com/docs/saving-state) functionality. Could you please elaborate?

Alan.

**Comment by ronsiverd** [comment]
That's great the delete key functionality will be coming, thanks!  Sorry about the explanation, I'll try and clarify it a little.  Currently to restore the markerarea state from a previous session you have to show the MarkerArea to get the changes (be in the editing mode either inline or through the popup when the marker area is showed).  What I would like to be able to do is grab the state from a previous session where I saved off the marker state with an image and automatically apply this to a photo when it is loaded on the page.  It would be nice if I could do this without having the show the marker area popup or be in the marker area editing mode.  From your example to be able to repeatedly make edits to an image, the demo has a second image overlayed on top of the first.  My thought is it would be nice if that overlayed image could already had a previous markup state applied to it the first time a user loads the image or page.  Hopefully this is a little clearer.  I am able to get this to work as it is, but I have to create a canvas image, apply the previous marker state to it, create an image from that canvas, and then overlay it as the second picture (not the original source image) now.  I was thinking this would be a nice enhancement to the project to make it easier for others to use as well.  Thank you!

**Comment by ailon** [comment]
You can just use [`renderMarkersOnly` setting](https://markerjs.com/docs/rendering-options) and get a transparent PNG that you can overlay on top of the original image with no overhead from the whole marker area rendering.

**Comment by ailon** [comment]
Delete key functionality was added in v2.4.0

**Comment by ronsiverd** [comment]
Thank you, Alan.  Sorry, I've been a bit swamped and meaning to get back to your comment on renderMarkersOnly.   I did see that feature and how it can be used to create a transparent image of just the markers, but I haven't figured out a way to use saved off marker details (from a previous session that I saved off into the database) to create just that overlayed transparent PNG.  I'll keep working at it to try and see what I am missing, but thankfully I have something else working right now.   Thanks again for your time and the great product!

**Comment by ailon** [comment]
There's no way to just generate the PNG from saved state without opening the marker area in editing mode.

**Comment by ronsiverd** [comment]
That's what I was thinking and thought may be a great addition to the markerjs2 library and is something our users like, as they can come back to their edits at anytime.  Thank you again for the response, Alan.

**Comment by ailon** [comment]
They can come back to their edits any time and you can save a PNG. You just have to save it at the same time as you save the state
