### ISSUE TITLE
Way to remove white background in popup view and specify image enlargement percentage?

### ISSUE THREAD

**Issue by zapatacarlos** [ailon/markerjs2#50]
Is there a way to get the popup view without the default white background and fit the marker area to the image at a certain enlargement percentage (in the popup view)? I tried using popupMargin but didn't make it.

**Comment by ailon** [comment]
You can change the background using [canvasBackgroundColor](https://markerjs.com/reference/interfaces/istylesettings.html#canvasbackgroundcolor)

Custom scaling of the image isn't possible at this point.

**Comment by zapatacarlos** [comment]
Thank you very much!
