### ISSUE TITLE
Some actions throw exceptions when nothing is selected

### ISSUE THREAD

**Issue by cravay** [ailon/markerjs2#51]
Hi, thanks for creating markerjs2!

I've noticed that some actions lead to exceptions being thrown, when nothing is selected:
* Pressing delete
* Changing any property of arrows, text and callouts

https://user-images.githubusercontent.com/11135559/128151799-693f796a-e5cf-4d0c-9e4b-55d070d6b7b4.mp4

**Comment by ailon** [comment]
Thank you for reporting this! I was able to reproduce it and will look into it soon.
