### ISSUE TITLE
Force RectangleMarkers and other markers to be reused after each creation

### ISSUE THREAD

**Issue by janrey1** [ailon/markerjs2#52]
Is there any way to set default markers to be selected and create multiple elements of the marker without clicking the toolbar every time an element is created?

Because right now when adding a FrameMarker, an ArrowMarker, or a TextMarker, the tool is automatically deselected after drawing.

**Comment by ailon** [comment]
Currently, there's no such option but it's on my to-do list. There are some user experience considerations that make this not a super easy option to add.

**Comment by ailon** [comment]
This is still not an exact built-in feature, but you can make something similar using the new events subsystem. [Here's a demo](https://markerjs.com/demos/events).
