### ISSUE TITLE
Is there a way to work with an image source's size? - thumbnail workaround

### ISSUE THREAD

**Issue by joshualeduc** [ailon/markerjs2#53]
I'm trying to build out a mobile UI with small square thumbnails.  I have full size preview image elements that are `display: hidden`, until the user taps on a thumbnail. I have an edit button to launch markerjs2 next to these thumbnails. I have tried:
1. feed markerjs the thumbnail img element
2. feed markerjs the `display: none` full size img element

Option 1 rewrites my source image to the size of the thumbnail, while option 2 makes markerjs2 error out. Specifically, option 2 brings up the tools with a white canvas in popup mode, and gives a `Failed to read the 'value' property from 'SVGLength': Could not resolve relative length` when trying to save.

Is there a way to preserve the source image while my ui is heavily based on thumbnails?

**Comment by ailon** [comment]
The simplest way would be to "unhide" your full-size preview, then open marker.js to annotate it and then when marker.js closes hide it again.

If that's not an option for some reason, a little more elaborate option would be to create a new image with the same source as your full-size image and then use marker.js on that. Here's a quick demo:
https://codesandbox.io/s/marker-js-2-annotate-hidden-image-tllbu
