### ISSUE TITLE
Confirm before cancelling

### ISSUE THREAD

**Issue by brunobg** [ailon/markerjs2#55]
Is there a way to confirm before closing? `addCloseEventListener()` seems to be too late to do anything about it. I'm trying to avoid a missclick on close that loses all data.

**Comment by ailon** [comment]
There's no way to control this right now but I'm planning on expanding the event system and this sounds like a good idea to add a cancelable "beforeclose" event (or something like that). Thanks!

**Comment by ailon** [comment]
This is now possible in 2.16 or higher. Docs [here](https://markerjs.com/docs/events)
