### ISSUE TITLE
Retro-compatibility for Firefox 51+

### ISSUE THREAD

**Issue by vdestremau** [ailon/markerjs2#56]
Hello,

We are developing a product that requires Firefox 52.9 and when trying to use the library, we found an issue with `cssRules` not being supported on that version.
We searched for this issue and found a solution that we can provide. We would like to buy the licence but it depends of this being fixed.   

Solution found : 
In the file `Style.ts` : 
- line 86 : replace `addRule` by `insertRule`
- line 102 : replace `rules` by `cssRules`

**Comment by ailon** [comment]
I will look into it. Looks like `addRule` and `rules` are deprecated either way. Need to investigate why they were used in the first place.

**Comment by ailon** [comment]
I've replaced the deprecated members (out in v2.14.1) but I don't think it works in Firefox 52 still (at least in my remote testing). It starts working on v59.

There are no errors in v52 console so it's hard to pinpoint the problem without digging deeper. Unfortunately, it's hard to justify investing a lot of time into supporting a browser so many versions behind the current. But if you manage to find what's stopping it now and there's an easy fix/workaround, I'm happy to incorporate it.
