### ISSUE TITLE
Is there  a polygon marker available out of the box ? 

### ISSUE THREAD

**Issue by elitz123** [ailon/markerjs2#61]
Hello. marker.js looks like it will be useful for my use case. As you can see on the attached screen shot, i am using it to outline rooms on a house floor plan drawing (jpg or png image). The outline is represented by an svg polygon annotation shape that effectively outlines a room of any shape. On top of that, i'd like to place text with a transparent background that i can position in a specific location on top of the underlying polygon shape. The text effectively identifies the name of the room. I've looked at the API and do not see a polygon shape built in.  Is there a polygon out of the box or would i need to write my own custom marker ?  Any  advice would be appreciated. 

thanks

![image](https://user-images.githubusercontent.com/5573076/141598207-fcfce726-29da-4002-8cc7-a27431b0c94f.png)

**Comment by ailon** [comment]
Hi. Thank you for reaching out! 

No, there's no built-in polygon marker. I assume what you mean would be something where you can build a polygon point-by-point (not just a preset set of polygons), right? That would add too much complexity beyond marker.js scope, in my opinion. You would need to add an ability to edit the polygon (move, add, remove individual points, etc) which is not what marker.js does at the moment. The goal is to provide easy annotation functionality, not a full-blown graphics editor.

**Comment by elitz123** [comment]
That's right. Not  a preset set of polygons, rather a polygon tool to support free form placement of the points around any portion of the underlying image. In some respects, it is quite similar to the rectangle tool (for example) in that it can be moved around, resized using handles, with a selectable stroke color. (in my case, i would also need a selectable fill color and opacity). The marker.js tool is really close to my needs. I started my search looking at something called "annotorious) (https://github.com/recogito/annotorious). That was close but not exactly aimed at my use case. THat developer recommended checking out marker.js. Perhaps i could work with you to freely contribute to your project by working on a polygon marker ? I would likely need a bit of direction from you to get started. Would that be a possibility ? 

thank you

**Comment by ailon** [comment]
Unfortunately, I can't accept contributions due to licensing issues. Also, as I mentioned, I don't think such a tool would fit in the current marker.js architecture and "philosophy". I can't really think of a user-friendly way for adding/removing points in the polygon that wouldn't require adding some extra UI concepts, and I'm not keen on adding extra complexity.

**Comment by elitz123** [comment]
OK. that's too bad. I have a paying customer that would be able to help fund this enhancement. 

One last question... i notice that you do have a polygon shape referenced in one of your core classes that creates the svg elements. Is this not at all related to what we're discussing ? 

![image](https://user-images.githubusercontent.com/5573076/141789866-fc013606-3fe7-4ea1-afc4-5efceefdc0ed.png)

**Comment by elitz123** [comment]
@ailon Hi Alan. Just checking back (see comments above) to see whether your situation has changed and/or whether you might be available for hire to enhance markerjs to include a polygon capability for a paying client ? Or possibly provide paid online tutoring sessions to me (a medium level javascript dev) to point me in the direction i would need to go to add this capability ? Figured it couldn't hurt to ask. 

thanks

elliot litz

**Comment by ailon** [comment]
Sorry, @elitz123, plans haven't changed and I still don't see a proper way to implement this without either massively complicating things or making a very rudimentary marker that wouldn't be very convenient to use.

In the latter case I imagine it's possible to make a marker where if you, say, double-clicked on a line/edge of the polygon it would add a point and a double-click on a point it would remove it. If this would work for you and you are willing to sponsor the development of such a marker, please reach out to alan@markerjs.com
