### ISSUE TITLE
toolboxBackgroundColor does nothing

### ISSUE THREAD

**Issue by yogster** [ailon/markerjs2#62]
Hello and thanks for this great piece of software - It's very useful and easy to integrate.

`IStyleSettings.toolboxBackgroundColor` should[ change the background colour of the toolbox](https://markerjs.com/reference/interfaces/istylesettings.html#toolboxbackgroundcolor), but does nothing.

Having a look at the code I can see it [defined in IStyleSettings](https://github.com/ailon/markerjs2/blob/68236db011da5bc206a4389ec0d17e3a4808b089/src/core/IStyleSettings.ts#L12) and [its default value assigned](https://github.com/ailon/markerjs2/blob/68236db011da5bc206a4389ec0d17e3a4808b089/src/core/Style.ts#L48), but not actually used anywhere.

**Comment by ailon** [comment]
Thank you for reporting this! I'll take a look and fix this.
