### ISSUE TITLE
containerTransformMatrix []

### ISSUE THREAD

**Issue by NarGhazaryan** [ailon/markerjs2#63]
How can I calculate the containerTransformMatrix, using top, left, width, height, and rotation angle?

**Comment by NarGhazaryan** [comment]
How can I render a FrameMaker, using these fields?

**Comment by ailon** [comment]
Do you mean that you just want to place a frame marker of specific size at specific coordinates? If so, I don't think there's a public way to do this. marker.js is an interactive tool for end-users to place markers. It doesn't have much control from the code side for things like this. But you can probably fake this with `restoreState()`. Just draw a marker manually and see what you get in the state.

But you probably don't need marker.js if you just need to draw a rectangle from code in a specific location.

Let me know, if I misunderstand what you are trying to achieve.

**Comment by NarGhazaryan** [comment]
Thanks for your reply.
My goal is to generate some standard markers, make it possible to edit them, and draw new ones.
At the moment I am trying to achieve the render of standard markers, for which I only have coordinates, dimensions, and rotation angle. As I understand it, for rendering you need a transformation matrix of the container. I was able to count the first 4 elements of the matrix, but I don't understand what e and f are responsible for. If you could tell me, I would be very happy :)

**Comment by ailon** [comment]
IIRC, I never calculated them by hand. The matrix is just an internal representation of applying transformations to SVG elements. See https://developer.mozilla.org/en-US/docs/Web/API/SVGTransform

To be honest, I wouldn't recommend you go this path as you are digging under the hood now and things may change in the future breaking your code. There's no public API for what you are trying to do. Creating a "state" that you can restore is the closest thing.

**Comment by ailon** [comment]
Oops, wrong issue tagged as fixed in that commit.
