### ISSUE TITLE
markerArea.addEventListener not triggered

### ISSUE THREAD

**Issue by balgopal14** [ailon/markerjs2#65]
Hi @ailon,

First of all thank you very much for this amazing tool!

In this below code save button event was not triggered but close event working fine.
```
function openImgPopup(fileId) {
          
          const markerArea = new markerjs2.MarkerArea(document.getElementById(`img-${fileId}`));
         
          markerArea.addEventListener(
            "render",
            (event) => (document.getElementById(`img-${fileId}`).src = event.dataUrl)
          );

          // make sure clicking close wasn't an accident
          markerArea.addEventListener("beforeclose", (event) => {
            if (!confirm("Do you want to discard changes?")) {
              event.preventDefault();
            }
          });

          markerArea.settings.displayMode = 'popup';
          markerArea.show();
          
}
```

Not sure what i'm doing wrong. Please take a look.

**Comment by ailon** [comment]
Hi @balgopal14 

Can't see anything wrong on the first glance. Here I've tried to basically reproduce what you are doing and it seems to be working:
https://codesandbox.io/s/marker-js-2-events-forked-6z21l?file=/src/index.js

**Comment by balgopal14** [comment]
Hi, I found the issue it will not work with AWS signed url because in local image it works fine

```
<img id="img-{{file.signedUrl.id}}" class="pointer" ng-src="{{file.signedUrl.url}}"
                                       ng-click="vm.openImgPopup(file.signedUrl.id)"
                                       alt="lab-order-pic-1"/>
                                   
<img ng-click="vm.openImgPopup(file.signedUrl.id)" id="img-{{file.signedUrl.id}}" class="search-digital-sample"  src="../../../../images/Digital_icon.png" alt="Digital_icon">
```

src img tag working fine but  ng-src="{{file.signedUrl.url}}" not executing render event.

**Comment by ailon** [comment]
So this is a CORS issue. Try setting `crossorigin="anonymous"` on the img. If that doesn't help, then it's a server-side issue.

**Comment by balgopal14** [comment]
After adding `crossorigin="anonymous" ` render event worked. But Now we have CORS issue. 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by ailon** [comment]
As I mentioned, in this case this is a server-side issue - you should configure CORS rules on the server serving the image file. I'm no expert in that, so, unfortunately, I can't be of much assistance. General information about CORS can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by balgopal14** [comment]
Thanks @ailon I will check the CORS issue.
