### ISSUE TITLE
Bold and plain text issue

### ISSUE THREAD

**Issue by Greencoad** [ailon/markerjs2#66]
while copy-pasting a text on an image and text containers some Bold and plain text characters the user is not able to  save the annotation. please have a look at the attached image
![marker issue 1](https://user-images.githubusercontent.com/64676251/146168713-1e6eb0b3-f086-499e-9029-425f1b9292ea.png)
![marker issue 2](https://user-images.githubusercontent.com/64676251/146168721-d4a9260f-fd44-476b-9142-d147d1b45d81.png)
![marker issue 3](https://user-images.githubusercontent.com/64676251/146168728-5f2dfda3-de34-4a45-8f32-f8679e2e98da.png)

the above images show the text taken and tested in edit mode of live website

**Comment by ailon** [comment]
Are you copying this from the web or some other place? Do you have a link to the exact place where you are copying this from? Also, what browser/OS is this?

**Comment by Greencoad** [comment]
hey, Ailon were you able to recreate the issue??

**Comment by ailon** [comment]
@Greencoad yes, I was able to reproduce, and I plan to work on it after the holidays. thanks!
