### ISSUE TITLE
Freehand drawing - line thickness issue

### ISSUE THREAD

**Issue by mathmax** [ailon/markerjs2#68]
![markerjs problem](https://user-images.githubusercontent.com/3242398/147942892-aa7a51d2-108f-4b91-b267-6f3b645a2bd7.png)
Hi,
Are you able to explain strange behaviour (shown in attached image) ? During drawing (upper row of images)  the line is thicker than after drawing (bottom row of images). It looks like a few pixels are disappearing on sections close to straight lines. 
In addition to the zommed part on the right side of the curve, a thinner line is also visible at the bottom. Is there any way to fix this? 
Best regards

**Comment by ailon** [comment]
Hi. By "during drawing" and "after drawing" do you mean right away when you finish drawing or when you press "save"? In the latter case, the difference can be due to rendering at natural size (for example) as some scaling happens and it's not pixel-perfect for raster images (like freehand marker).

**Comment by mathmax** [comment]
Hi, By „during drawing” I mean when i move a mouse with mouse button pressed to leave the trace on the screen;By „after drawing” I mean the moment just after releasing mouse button and stop drawing.Best regardsNorbertSent using the mobile mail appOn 1/4/22 at 10:34 AM, Alan Mendelevich wrote:
                
            
            
                
                    From: "Alan Mendelevich" ***@***.***>Date: January 4, 2022To: "ailon/markerjs2" ***@***.***>Cc: "mathmax" ***@***.***>,"Author" ***@***.***>Subject: Re: [ailon/markerjs2] Freehand drawing - line thickness issue (Issue #68)
                
                
Hi. By "during drawing" and "after drawing" do you mean right away when you finish drawing or when you press "save"? In the latter case, the difference can be due to rendering at natural size (for example) as some scaling happens and it's not pixel-perfect for raster images (like freehand marker).

**Comment by ailon** [comment]
Hmm... In this case I don't do anything special - standard `canvas.closePath()` is called when you release the button which probably causes some internal finishing touches in the browser's canvas code. I don't know if anything can be done about it.

**Comment by mathmax** [comment]
comparing the drawn image and the saved one (after pressing save), the latter has antialiasing around the lines, while the original does not show it. Is it possible to turn off the anti-aliasing when rendering only overlay to file?
