### ISSUE TITLE
Picture as overlay

### ISSUE THREAD

**Issue by beeing** [ailon/markerjs2#7]
Hi there, found out this awesome library and interested to add this to my project.

However, I needed to add a transparent image on another image as the marker, which it should be scaled, moved and rotated.

Will this be considered?

Thanks in advance.

**Comment by ailon** [comment]
I'm not 100% sure I understand what you are after.

You can generate just the markers as a transparent PNG using `renderMarkersOnly` setting and then overlay it on top of your original image when and as you need it.
https://markerjs.com/docs/rendering-options

**Comment by beeing** [comment]
Ok thanks. Will give this a try.
