### ISSUE TITLE
Differentiating between keyboard and button events

### ISSUE THREAD

**Issue by kim3er** [ailon/markerjs2#70]
The `beforedelete` and `delete` events can originate from either a button or the keyboard. It would be very helpful to differentiate between the origins, say if you wanted to cancel the delete if a the keyboard is pressed.

Our specific use case is that we can have multiple marker areas on a single page, that coexist with other field types. Our marker areas are activated from the word go. As marker areas are all focused straight away, they're all listening to the global key up event.

To manage this, we use a synthetic `blur` event to decide which marker area should be listening to the event (if any). If we could cancel just the keyboard event, rather than the button event, we could keep each marker area active.

**Comment by ailon** [comment]
Would a simple setting to straight up disable deleting markers from the keyboard solve your immediate problem?

**Comment by kim3er** [comment]
I think that would be a very nice setting to have, we'd absolutely make use of it. It would be great if we could tell the origin of an event as well. Short term, either option would be great.

**Comment by ailon** [comment]
Origin of the event would require extending the whole event system (I think) which I'm not eager to jump on if a simpler solution would address your use-case.

**Comment by kim3er** [comment]
Totally get that. Then let's go with the simpler solution.

**Comment by ailon** [comment]
Btw, have you thought about "blurring" all marker areas after opening and then using `focus` events to blur all the other marker areas (except for one that got focus) on that page? This should be transparent to the end-user while disabling global events on other areas.
