### ISSUE TITLE
Render as a server component

### ISSUE THREAD

**Issue by kim3er** [ailon/markerjs2#72]
Have you ever considered, or do you think it is already possible to run the render workflow on a server?

Our use case is that as we move toward using the state functionality of markerjs2, we're deciding when the right time to render is. Our feeling is that it, would be optimal if we could just store the state, and request a render to generate a read only view, or even a PDF. In those scenarios, there may not even be a web browser open, let alone an instance of MarkerArea to interact with.

I feel like we could probably attach a MarkerArea to virtual DOM (I don't think I've made that up), and deal with it that way. But wondered if you had a any thoughts on a purpose built solution?

**Comment by ailon** [comment]
I don't have any personal experience with this but I don't see why rendering with a server-side instance of Chrome wouldn't work.

I don't know your complete scenario but have you considered using marker.js Live and not rendering at all?
