### ISSUE TITLE
renderWidth and renderHeight not taken into account for the freehand drawing tool

### ISSUE THREAD

**Issue by kdorion** [ailon/markerjs2#73]
Hello, I'm actively developing a tool using this library to annotate videos and it's going pretty well, very nice library! We will be purchasing our license soon before using it in production.

When explicitly setting renderWidth and renderHeight and the freehand drawing tool, it seems like the canvas should be sized appropriately so that if renderWidth and renderHeight is bigger than the current screen size, it won't be "pixelized" upon rendering at the specified renderWidth and renderHeight dimensions.

Example with renderWidth and renderHeight set to 1024:
https://codesandbox.io/s/marker-js-2-all-defaults-demo-forked-rwyrv?file=/src/index.js
1- Make the preview screen (or open the standalone app at https://rwyrv.csb.app/) and resize the screen to be as small as a phone display (400px wide for example)
2- Open the marker viewer by clicking on the image
3- Use the freehand drawing tool and draw some stuff
4- Press the checkmark to render
5- resize the screen to be 1024px wide, the drawings on the resulting image is all pixelized. 

It seems that this issue is also reproducible when using the renderAtNaturalSize setting (which I can't use in my case because i'm on videos, so I thought of using renderWidth and renderHeight)

Thank you!

edit: adding some more details that is somewhat related since it has to do with canvas rendering: when drawing on a canvas, you probably also want to account for device pixel ratio of the device you are currently drawing on. See https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

**Comment by ailon** [comment]
FreeHand marker is the only marker type that is canvas-based (raster) so it doesn't scale like the others do. There's nothing we can do about this issue. It's by design.

**Comment by kdorion** [comment]
Like I mentioned, you can set the width and height of the canvas so that it has a greater resolution than what is displayed in the viewport. If you look at the device pixel ratio example I posted from MDN, it's the same concept that you would have to apply.
I know it's not a vector but there are strategies to make it look better

**Comment by ailon** [comment]
Oh, sorry. I was replying to the issue notification email and that didn't include your edit. So I haven't noticed it :)

I will look into this, but I'd need to figure out how this affects cross-device sessions and backwards compatibility. Thank you for the pointers.

**Comment by kdorion** [comment]
I think you mentioned somewhere you are not opened to PRs due to licensing issues, but let me know if I can be of any help. 
Thank you!
