### ISSUE TITLE
When resizing the window, the active tool loses its active state/class

### ISSUE THREAD

**Issue by kdorion** [ailon/markerjs2#75]
https://codesandbox.io/s/markerjs-2-customize-ui-b8ows?file=/src/index.js:1024-1148
- Click on the image
- Select a tool, say the ellipse tool
- resize the window so that the image gets resized
- Notice the tool doesn't have the "active" styles anymore
- You are still able to create an ellipse by clicking on the image since the tool is still selected, even though you don't see it.

**Comment by ailon** [comment]
Thank you for reporting! I will look into it and fix.
