### ISSUE TITLE
Popup option height on tablet/mobile devices gets a strange height value.

### ISSUE THREAD

**Issue by noudadrichem** [ailon/markerjs2#77]
Hi, thank you for making this amazing tool! 
It's been really use full to me. The problem I'm facing is that on tablet/mobile sizes the height of the popup get's a lot higher as the viewport. (See video for more context)

https://user-images.githubusercontent.com/16288476/158397465-60f289e6-0004-4930-b9ab-d1de6bfef612.mov

What I'm trying to achieve is having the marker 'editor' to be full screen on tablet and mobile as well. So even remove the 'black' borders around the popup. I hacked together some additional CSS on laptop/desktop that works. But it breaks on mobile/tablet devices.

Also maybe a bit of more context on what I'm trying to achieve as well:
<img width="964" alt="Screenshot 2022-03-15 at 15 16 39" src="https://user-images.githubusercontent.com/16288476/158398051-eecf8a47-6b4d-4ae4-90c5-459590d985b3.png">
 
So, I'm not sure if this is intended or a bug. The same happens on my mobile phone when I try the popup example from the website. I hope you can point me into a direction on how to achieve what I want because I'm unable to make this work on phone/tablet for now. Let me know!

**Comment by ailon** [comment]
Hi there,

You can change the "black border" size by setting `markerArea.settings.popupMargin`
https://markerjs.com/reference/classes/settings.html#popupmargin

As for the sizing issue, I wasn't able to reproduce it so far. Is this Chrome in your video? And do I understand correctly that you see the same effect on the demo page [here](https://markerjs.com/demos/popup)?

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/179076/158547109-ae0e4586-6218-434e-86d3-4bc522b88c75.png">

Seems to be working fine for me.
