### ISSUE TITLE
Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite. 

### ISSUE THREAD

**Issue by GobindaSaha** [ailon/markerjs2#79]
![Screen Shot 2022-03-31 at 7 48 06 PM](https://user-images.githubusercontent.com/34857385/161077005-5571cec3-c022-4401-a7cf-d9cd673aa2da.png)

Don't know why this error showing again and again. Did I missed something? Please suggest me.

**Comment by ailon** [comment]
Is there any context? Impossible to say anything without understanding what you are doing and how.
