### ISSUE TITLE
Support of Zoom / Pinch-zoom

### ISSUE THREAD

**Issue by beeing** [ailon/markerjs2#8]
Hi @ailon, I'm interested to use this in mobile device where user can zoom into an image to have better annotation.

Doing a search, I didn't not find anything related to zoom. Is part of your development roadmap?

Thanks.

**Comment by ailon** [comment]
There are no current plans to add zooming of an underlying image directly in marker.js. It sounds like it would be quite an undertaking to do it properly.

Is just zooming the surrounding page not a viable option?

**Comment by beeing** [comment]
Thanks for the quick response.

There are some libraries out there which can do pinch zoom or even we can add a simple slider bar to zoom in / out. However markerjs will placed an overlay layer which prevent us to zoom while doing annotation.

**Comment by beeing** [comment]
Unless you can suggest a way to zoom the page? Can give it a try if that's usable.

**Comment by ailon** [comment]
Hmm.. I'll think about. I guess I can pass pointer events through if it involves more than one finger. That however could potentially break in the future if I add pinch-to-zoom or other gestures to marker.js.

**Comment by beeing** [comment]
For the zoom, I'll also need the panning.

I was thinking if there's a toolbar button for user to toggle the zoom and pan mode and the operations are done on the overlay and in-synced with the underlying image or so.

Hope there's good solution for this. Thanks again.

**Comment by beeing** [comment]
Hi @ailon, is there any updates on this? I'm still interested to use markerjs2 but we'll need this feature though.

**Comment by beeing** [comment]
Ok, if passing the events through for zoom, how about the markerjs layer? Does it aware of the scale ratio? As the annotation will need to be scaled together with the backend.

**Comment by ailon** [comment]
What I meant is that if I pass the events through it would enable the surrounding page/browser window to zoom in. I don't expect any effect on marker.js from that (the whole thing including toolbars would zoom in/out)

**Comment by beeing** [comment]
Yes, I can give it a try once you add in the passthrough event. Perhaps we'll know what tweaks needed later.

**Comment by ailon** [comment]
OK, I'll add it in the next release (hopefully next week).

**Comment by beeing** [comment]
Thanks and looking forward to it.

**Comment by beeing** [comment]
Hi @ailon thanks for the updates. Btw, how do we use this? Need to pass in any options?

**Comment by ailon** [comment]
No, I just changed it to pass multi-touch events up the tree. The browser should handle them in a default way now.

**Comment by beeing** [comment]
Ok, thanks.
