### ISSUE TITLE
markerselect event fires when resizing window

### ISSUE THREAD

**Issue by vincentneo** [ailon/markerjs2#82]
Thanks for making this library!

Just a minor issue that I observed. 

The `markerselect` event seems to fire a couple of times after a window resize, when a marker is selected. I believe that event should only fire at the moment where user selected the marker, and thought this could be a bug, hence opening this issue. 

I'm using the latest version of markerjs2 (2.21.3). 

In case it matters, the display mode that I am using is `popup` rather than the default `inline`.

**Comment by ailon** [comment]
Yes, I think you are right. The current marker is deselected when resizing happens and then selected again which causes the event "misfire". I will look into it and hopefully find a decent solution.
