### ISSUE TITLE
Bug on wanting to draw a rectangle over a freehand drawing?

### ISSUE THREAD

**Issue by Dima-369** [ailon/markerjs2#83]
I have tested this on the latest `master` on Firefox.

Here is a video. I want to first freehand draw and then just draw a rectangle around it.

As soon as I hit the rectangle after freehand drawing in the top menu, it jumps to the Pointer action (while still displaying line thickness and color in the bottom menu) and then on clicking inside the canvas, it renders a mini rectangle incorrectly but also moves the freehand drawing around.

It is reproducible with some other actions as well, for instance using an ellipsis.

https://user-images.githubusercontent.com/15002298/167701756-07175827-711e-4088-af7f-6f08a695cdda.mov

**Comment by ailon** [comment]
Hi there. Thanks for reporting this. I can see some weird behavior with freehand marker in Firefox. Looks like some default browser dragging action kicks in on top of marker.js behavior. I'll look into it.

**Comment by ailon** [comment]
Sorry, this took this long but I didn't have any actionable ideas on how to address this at the time and just decided to try to tackle it one more time. This time I can't reproduce it on the current version. So either some other change/fix addressed this issue as well, or Firefox fixed something in the way it handles these scenarios. There's also a possibility I'm just failing to reproduce it this time :) If that's the case please let me know and I'll reopen this issue.

**Comment by Dima-369** [comment]
I can also not reproduce it for whatever reason :)
