### ISSUE TITLE
Save automatically without render (save button)

### ISSUE THREAD

**Issue by KovaZg** [ailon/markerjs2#85]

**Comment by KovaZg** [comment]
Best workaround that doesn't flicker is with this code, maybe it helps someone:

`function restoreMarker(target){
    const markerArea = new markerjs2.MarkerArea(sourceImage);
    markerArea.targetRoot = targetRoot;
    markerArea.uiStyleSettings.hideToolbar = "true"; 

    markerArea.addRenderEventListener((imgURL, state) => { 
        // save the state of MarkerArea
        target.src = imgURL;
        maState = state;
      });

    markerArea.show();
    // if previous state is present - restore it
    if (maState) {
      markerArea.restoreState(maState);
    }

    markerArea.startRenderAndClose();
}`

**Comment by ailon** [comment]
FYI, there's a `renderState()` method specifically for the scenario you are after:
https://markerjs.com/reference/classes/markerarea.html#renderstate
