### ISSUE TITLE
Cannot pass marker from one page to another browser cuts it out

### ISSUE THREAD

**Issue by KovaZg** [ailon/markerjs2#86]
1. I have a form page (INSERT) with 3 images 
2. Image 1 [
![image](https://user-images.githubusercontent.com/5083743/168493685-458827fa-9ecb-454b-ae39-1c89c6f80ade.png)
](url)
Image 2 [
![image](https://user-images.githubusercontent.com/5083743/168493707-5c6951a2-c7dc-4be5-a4e4-02e241ba44d5.png)
](url)
Image 3 [
![image](https://user-images.githubusercontent.com/5083743/168493719-a35bf3fe-12aa-41a1-903e-906478d499f7.png)
](url)
3. Before I put marker data (maState) to hidden field I crypt it to make it smaller
`maState = state;
  image1state=JSON.stringify(maState);
  var encrypted = CryptoJS.AES.encrypt(image1state, "Secret Passphrase");
  document.getElementsByName("idimage1")[0].value=encrypted.toString();`
5. Storing encrypted marker state into database
6. Extracting from database on EDIT page
7. Restoring maState to any of 3 images, huge chances are that at least 1 or 2 will not work, in some cases I can't pass one marker, and in rear occasions all three are displayed good.

**Comment by ailon** [comment]
Hi there. Not sure I understand the issue fully. Some questions to clarify:

1. Do you try to open all 3 marker areas at once?
2. Does encrypting the state make any difference? Is this part relevant for the issue you are facing?
3. Can you create a repro on codesandbox.io (or anywhere else) so I can see the issue? Alternatively, please show me more code.

**Comment by KovaZg** [comment]
1. Yes I try and I have managed to display all 3 ok. But it is random. Sometimes just first shows. 
2. I do not think so, when I did it with one with smaller amount of markers on the image, worked just fine. Never a issue. 
3. I will make it, will reply or edit this comment once I make it. 
4.

**Comment by KovaZg** [comment]
Thanks Ailon, just to make it clear I do not open multiple areas, I just
want to show all 3 old states and each area is opened on click.

**Comment by KovaZg** [comment]
Alion, I think I found my issue, it was onload in each img line, I sure hope so, now I made function that runs on load, and there I do all source images, all markers show on all 3 images.
