### ISSUE TITLE
Error with the backspace-to-delete feature

### ISSUE THREAD

**Issue by jeffinmotion** [ailon/markerjs2#9]
Hi Alan,

Thanks for adding the feature in 2.4.0 that enables marker deletion with the backspace keystroke, very helpful!

Unfortunately now if you use the backspace key while typing text into a text-based marker, it deletes the marker as you're typing.

Jeff

**Comment by ailon** [comment]
Thank you for reporting this. Yes, looks like a new bug. I'll fix it.
