### ISSUE TITLE
Help with custom markers which includes arrow, circle and number

### ISSUE THREAD

**Issue by anounbobo** [ailon/markerjs2#91]
I would like to create a custom marker which include an Arrow, a Circle and also a Number (see attachment-file).

It would be really appreciate if you can help me with that.

best regard.

![arrow-custom](https://user-images.githubusercontent.com/106995319/172219788-b902cf92-3bdd-4a2a-83c5-7fc2a17d1268.PNG)
s

**Comment by ailon** [comment]
Hi @anounbobo. I'm missing an issue or a question in your message ;) 

If the question is whether I can create this marker for you, then, sorry, I don't have the time to build customer markers. If you are looking for useful pointers to where to start, then start here:
https://markerjs.com/docs/extend-markerjs
