### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'clientWidth')

### ISSUE THREAD

**Issue by anubhabmondalDirac** [ailon/markerjs2#93]
Hi everyone,
i am using marker.js cnd version for my website . Everything works fine in standalone also store and restore property. but when i put it in my website i am getting this error **Uncaught TypeError: Cannot read properties of undefined (reading 'clientWidth')** and that toolbar of marker.js did not load. Can you please help me on this ? @ailon 
Thanks in advanced.

**Comment by ailon** [comment]
hey, I'd need some more information to be able to suggest something. Ideally a repro on codesandbox or something, but if this isn't possible then at least some stack trace and more error information from devtools to get started.

**Comment by anubhabmondalDirac** [comment]
So if we want marker.js for multiple images . how to achive that 

`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>All defaults demo</title>
  <script src="https://unpkg.com/markerjs2/markerjs2.js"></script>
  <script>
    let sourceImage, targetRoot, maState;

    // save references to the original image and its parent div (positioning root)
    function setSourceImage(source) {
      sourceImage = source;
      console.log("In save==",sourceImage);
      targetRoot = source.parentElement;
      console.log("In ==",targetRoot);
    }

    function showMarkerArea(target) {
      console.log("In save");
      const markerArea = new markerjs2.MarkerArea(sourceImage);
      // since the container div is set to position: relative it is now our positioning root
      // end we have to let marker.js know that
      markerArea.targetRoot = targetRoot;
      markerArea.addEventListener("render", (event) => {
        target.src = event.dataUrl;
        // save the state of MarkerArea
        maState = event.state;
        const myJSON = JSON.stringify(maState);
		console.log(maState);
    console.log("Height==",myJSON);
      });
      markerArea.show();
      // if previous state is present - restore it
    var maState= '{"width":600,"height":338,"markers":[{"color":"#EF4444","fontFamily":"Helvetica, Arial, sans-serif","padding":5,"text":"your text here","left":207,"top":117,"width":130,"height":51,"rotationAngle":0,"visualTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"containerTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"typeName":"TextMarker","state":"select"},{"drawingImgUrl":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFwAAABqCAYAAAAxzDboAAAAAXNSR0IArs4c6QAABVZJREFUeF7tnc+PFEUUx181zICIWWrBGDXBcPDswT+AMNO9yQYSDAkHD5w9GU9688KRiyF68A/wqglimITpYiGEIxy4mpgQgpso2R6NYXd2Z/qZnp/V3dXTv2tmt96cdmeq3+v91Hdev1e/loH0en3p0rVzW1u/yO/Rz9USYF67jcDY2CoicCEmv1TriKyNCRBwzUog4ARcMwHN7kjhBFwzAc3uSOEEXDMBze5I4QRcMwHN7kjhBFwzAc3uSOEEXDMBze5I4QRcMwHN7kjhBFwzAc3uSOEEXDMBze5I4QRcMwHN7kjhBFwzAc3uSOEEXDMBze7CCgcA7rq08qrGTogBD3wR9PqIj9Ts2TaGXCAiF8Kqz625lmfhIwqdVF6PKObA2+0BMHZMctPnrnuyHrfmWg09IEMqp6XLtagiDLzd9oFNF4uP1ov7XAhZ9bXchElGYykgxfJ6uz8OvN0eAmPzDIUylkp7QFnkhLahAMBgd/fqu0+e/FqpZ0ONKYHjjRvne9vbL2ZMSOWVySOxjPeiD1CAH7jrflmZZ0MNJQN3nG8B8SapvFplLByoiqocAbbWXbdV7S2YZW0h8H8c5zcf8bKkctrHWVIfqUOx0YyFxljKEU8H3mrtgWWdoFheDvT06lTgquFbUnlx+NmAR1JEi7F7a93uPLYX92/clZmA/3Xx4maj0bhHYaW8PjIBp7BSHnSuGD4CHp2gQOxzIWiCImdfZFZ4TOU0QZET9bh5PuDR8ZWDgz5/9IhUngN9LuAUy3OQTWiaH3h8Gm7IhThe/lbMsJAbOKm8nDCKAW+1fLCs+bU0QZG5FwoBJ5Vn5htrWBx4qzUAy5ovoSCVZ+qFwsBVKgfEO1yIzzJ5NrRROeAbG3+A71+Q2dFI4mIllQI+KfnnJ3sGb1BoWUi8NPCE0ELLnasqfFR2PNv+GQCuhT7z/SF/8IAKogiwShQ+Unk0axmHl+dciE8MfT4q/+zKgE9CyxAAQjsn/EZj7Wyn8y9BHxOoFPjkIRpd8kzxXFJb5cCpCq05LUwyH9lNQSqfgKpF4arQQgVRTTFcVjypPP79r03hpHJ1sK0VeOwBSmV/9WlhtF+jS55Nj+W1KxyvXz/f8zzavlJ3lhJ6eEYmnk1Wee0KD8Dv2PbXDOCW3AmmQtcCXFnyG3pMiDbgqpI/eM80pWsFroRuWKqoHbgKetPzPn376dNnJgzhLgW4yQXR8oAbmiouDbipKl8ucAP/eerqADckRVwp4KMsBTF8pF/QEUfoSL/VA56UG447Yvi62Tz9cafTP6wp5HKBB+vMg0PNpHPNMoNExOPN5nvvdDp/Z75mBRouFXhsRFG1bCOtMxDxzKlTp9ndu29WgGfqLawM8KQ7fXPlyof93d2XoeP9VI0RkTG2f2bFD7dceeAy2983N0+c29//DwCOZekAAAhC1ivuuh+lSk9Tg0MFPG36LhOzJQ+WHWrgU8CKA9HS2S8J/JEALtPt2fYeIjZTQ870onG6OeBCNNN7qXyLIwdchcTb2PgJhsPPR4tX5bN1F+X8lvU973a/Ko84bMEI4KViv1T5VlHxGgm8TOxHxrbXu90PiirfaOAK5R9kTTmLqp2AJ0jVc5zb4PvB0a+Lhh6G3HVz7WMi4Bljw47j/MkQ309oHuzK/obfv/9dmjkCnkYo8rln27F9THITRNxbF+KtJLMEPCfwafOebQ8wGGJIeCWttyHgBYFL4PcRoKEygwA76657Vv6MgJcEPgPvOF8g4o8Kcz533dk3gYBXBHyW29t2DwDWImaDuP8YAB4S8IqBS+B91T5YAl4T8MBsz7Zj8f1/jFSWa5qRFd0AAAAASUVORK5CYII=","left":123,"top":112,"width":92,"height":106,"rotationAngle":0,"visualTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"containerTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"typeName":"FreehandMarker","state":"select"},{"color":"#EF4444","fontFamily":"Helvetica, Arial, sans-serif","padding":5,"text":"Anubhab","left":436,"top":59,"width":141,"height":238,"rotationAngle":0,"visualTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"containerTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"typeName":"TextMarker","state":"select"},{"fillColor":"#EF4444","strokeColor":"#EF4444","strokeWidth":3,"strokeDasharray":"","opacity":1,"left":335,"top":43,"width":140,"height":116,"rotationAngle":0,"visualTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"containerTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"typeName":"EllipseMarker","state":"select"},{"color":"#EF4444","fontFamily":"Helvetica, Arial, sans-serif","padding":5,"text":"Sanu","left":145,"top":54,"width":128,"height":47,"rotationAngle":0,"visualTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"containerTransformMatrix":{"a":1,"b":0,"c":0,"d":1,"e":0,"f":0},"typeName":"TextMarker","state":"select"}]}';
const obj= JSON.parse(maState);
      if (obj) {
        markerArea.restoreState(obj);
      }
    }
  </script>
</head>
<body>

  <div style="position: relative; display: flex; flex-direction: column; align-items: center; padding-top: 50px;">
    
    <img src="img.jpg" crossorigin="anonymous" style="max-width: 600px;" onload="setSourceImage(this);"/>
   <img src="img.jpg" crossorigin="anonymous" style="max-width: 600px; position: absolute;" onclick="showMarkerArea(this);" />
  </div>
  <div style="position: relative; display: flex; flex-direction: column; align-items: center; padding-top: 50px;">
    
    <img src="img1.jpg" crossorigin="anonymous" style="max-width: 600px;" onload="setSourceImage(this);"  />
    <img src="img1.jpg" crossorigin="anonymous" style="max-width: 600px; position: absolute;" onclick="showMarkerArea(this);" />
  </div>
</body>
</html>
`
Thanks!!

**Comment by ailon** [comment]
You create a new `MarkerArea` for each of the images:

```
const markerArea = new markerjs2.MarkerArea(target); 
```

You pass a `target` to that `showMarkerArea()` function for each image.

**Comment by anubhabmondalDirac** [comment]
but if add this same code in my project i get this error message **Uncaught TypeError: Cannot read properties of undefined (reading 'clientWidth'**

**Comment by anubhabmondalDirac** [comment]
also that error **Uncaught ReferenceError: setSourceImage is not defined
    at HTMLImageElement.onload **

**Comment by ailon** [comment]
`setSourceImage()` is your function. I'm sorry but debugging your custom code is a bit out of scope here ;)
