### ISSUE TITLE
Keyboard entry on mobile

### ISSUE THREAD

**Issue by mharper6008** [ailon/markerjs2#96]
I would like to use this for both markup on the browser as well as inside of our mobile app (Ionic V1).  Everything seems to work fine with the exception of not being able to change text when dropped onto image.  There is no keyboard prompt or ability to edit the placeholder text.  Is this a known limitation, or something I am doing wrong in my app?  Thank you.

**Comment by ailon** [comment]
There are no specific limitations for a scenario like this, as far as I know. I don't know much about Ionic though. Does it happen (or rather not happen) on both iOS and Android? I remember there was an issue with keyboard coming up and then disappearing on some mobile setup as the keyboard popping up triggered a resize. But this is not what's happening to you, right? You just never see the keyboard if I understand correctly.

I'm not sure how all of this works but could it be that Ionic hardcodes some older version of WebView control?

These are some thoughts, but I'm afraid I don't know enough to be able to really help. Sorry.
